/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.tables.records.AtkChannelsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AtkChannels extends TableImpl<AtkChannelsRecord> {

    private static final long serialVersionUID = 493237449;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.ATK_Channels</code>
     */
    public static final AtkChannels ATK_CHANNELS = new AtkChannels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AtkChannelsRecord> getRecordType() {
        return AtkChannelsRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.ATK_Channels.client_id</code>.
     */
    public final TableField<AtkChannelsRecord, Integer> CLIENT_ID = createField("client_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.ATK_Channels.Finance_Channel</code>.
     */
    public final TableField<AtkChannelsRecord, String> FINANCE_CHANNEL = createField("Finance_Channel", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.ATK_Channels.ATK_Channel</code>.
     */
    public final TableField<AtkChannelsRecord, String> ATK_CHANNEL = createField("ATK_Channel", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.ATK_Channels.touchpoint</code>.
     */
    public final TableField<AtkChannelsRecord, String> TOUCHPOINT = createField("touchpoint", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.ATK_Channels</code> table reference
     */
    public AtkChannels() {
        this(DSL.name("ATK_Channels"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.ATK_Channels</code> table reference
     */
    public AtkChannels(String alias) {
        this(DSL.name(alias), ATK_CHANNELS);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.ATK_Channels</code> table reference
     */
    public AtkChannels(Name alias) {
        this(alias, ATK_CHANNELS);
    }

    private AtkChannels(Name alias, Table<AtkChannelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AtkChannels(Name alias, Table<AtkChannelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AtkChannels(Table<O> child, ForeignKey<O, AtkChannelsRecord> key) {
        super(child, key, ATK_CHANNELS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AtkChannels as(String alias) {
        return new AtkChannels(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AtkChannels as(Name alias) {
        return new AtkChannels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AtkChannels rename(String name) {
        return new AtkChannels(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AtkChannels rename(Name name) {
        return new AtkChannels(name, null);
    }
}
