/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.Indexes;
import jooq.cartrawler_dev_internal.dbo.Keys;
import jooq.cartrawler_dev_internal.dbo.tables.records.ChannelsippsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Channelsipps extends TableImpl<ChannelsippsRecord> {

    private static final long serialVersionUID = 1809859012;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.ChannelSIPPs</code>
     */
    public static final Channelsipps CHANNELSIPPS = new Channelsipps();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChannelsippsRecord> getRecordType() {
        return ChannelsippsRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.ChannelSIPPs.id</code>.
     */
    public final TableField<ChannelsippsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.ChannelSIPPs.ref</code>.
     */
    public final TableField<ChannelsippsRecord, Integer> REF = createField("ref", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.ChannelSIPPs.SIPP</code>.
     */
    public final TableField<ChannelsippsRecord, String> SIPP = createField("SIPP", org.jooq.impl.SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.ChannelSIPPs</code> table reference
     */
    public Channelsipps() {
        this(DSL.name("ChannelSIPPs"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.ChannelSIPPs</code> table reference
     */
    public Channelsipps(String alias) {
        this(DSL.name(alias), CHANNELSIPPS);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.ChannelSIPPs</code> table reference
     */
    public Channelsipps(Name alias) {
        this(alias, CHANNELSIPPS);
    }

    private Channelsipps(Name alias, Table<ChannelsippsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Channelsipps(Name alias, Table<ChannelsippsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Channelsipps(Table<O> child, ForeignKey<O, ChannelsippsRecord> key) {
        super(child, key, CHANNELSIPPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHANNELSIPPS_PK_CHANNELSIPPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ChannelsippsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CHANNELSIPPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ChannelsippsRecord> getPrimaryKey() {
        return Keys.PK_CHANNELSIPPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ChannelsippsRecord>> getKeys() {
        return Arrays.<UniqueKey<ChannelsippsRecord>>asList(Keys.PK_CHANNELSIPPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Channelsipps as(String alias) {
        return new Channelsipps(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Channelsipps as(Name alias) {
        return new Channelsipps(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Channelsipps rename(String name) {
        return new Channelsipps(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Channelsipps rename(Name name) {
        return new Channelsipps(name, null);
    }
}
