/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.Indexes;
import jooq.cartrawler_dev_internal.dbo.Keys;
import jooq.cartrawler_dev_internal.dbo.tables.records.ComputedvaluesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Computedvalues extends TableImpl<ComputedvaluesRecord> {

    private static final long serialVersionUID = -1078813230;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.computedValues</code>
     */
    public static final Computedvalues COMPUTEDVALUES = new Computedvalues();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ComputedvaluesRecord> getRecordType() {
        return ComputedvaluesRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.fk_reservation</code>.
     */
    public final TableField<ComputedvaluesRecord, Integer> FK_RESERVATION = createField("fk_reservation", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.revenue</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> REVENUE = createField("revenue", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.commission</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> COMMISSION = createField("commission", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.ancillaries</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> ANCILLARIES = createField("ancillaries", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.insurance_commission</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> INSURANCE_COMMISSION = createField("insurance_commission", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.netAmountBilledEuro</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> NETAMOUNTBILLEDEURO = createField("netAmountBilledEuro", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.processingFeeEuro</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> PROCESSINGFEEEURO = createField("processingFeeEuro", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.pleaseRecompute</code>.
     */
    public final TableField<ComputedvaluesRecord, Boolean> PLEASERECOMPUTE = createField("pleaseRecompute", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.lastComputeTime</code>.
     */
    public final TableField<ComputedvaluesRecord, Timestamp> LASTCOMPUTETIME = createField("lastComputeTime", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.bookingFeeMistake</code>.
     */
    public final TableField<ComputedvaluesRecord, Boolean> BOOKINGFEEMISTAKE = createField("bookingFeeMistake", org.jooq.impl.SQLDataType.BIT.defaultValue(org.jooq.impl.DSL.field("((0))", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.due2supplier</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> DUE2SUPPLIER = createField("due2supplier", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.provisionalRevenue</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> PROVISIONALREVENUE = createField("provisionalRevenue", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.provisionalCommission</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> PROVISIONALCOMMISSION = createField("provisionalCommission", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.commissionInSettlementCurrency</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> COMMISSIONINSETTLEMENTCURRENCY = createField("commissionInSettlementCurrency", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.revenueInSettlementCurrency</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> REVENUEINSETTLEMENTCURRENCY = createField("revenueInSettlementCurrency", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.provisionalCommissionInSettlementCurrency</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> PROVISIONALCOMMISSIONINSETTLEMENTCURRENCY = createField("provisionalCommissionInSettlementCurrency", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.due2Franchisee</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> DUE2FRANCHISEE = createField("due2Franchisee", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.provisionalInsuranceRevenue</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> PROVISIONALINSURANCEREVENUE = createField("provisionalInsuranceRevenue", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.cash_balance</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> CASH_BALANCE = createField("cash_balance", org.jooq.impl.SQLDataType.NUMERIC(10, 2), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.axa_fronting_fee</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> AXA_FRONTING_FEE = createField("axa_fronting_fee", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.axa_captive_ct</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> AXA_CAPTIVE_CT = createField("axa_captive_ct", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.axa_captive_axa</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> AXA_CAPTIVE_AXA = createField("axa_captive_axa", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.axa_taxes</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> AXA_TAXES = createField("axa_taxes", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.refund_rev</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> REFUND_REV = createField("refund_rev", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.refund_cost</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> REFUND_COST = createField("refund_cost", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.fin_details</code>.
     */
    public final TableField<ComputedvaluesRecord, Short> FIN_DETAILS = createField("fin_details", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.supplier_recharge</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> SUPPLIER_RECHARGE = createField("supplier_recharge", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.ins_refund_cost</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> INS_REFUND_COST = createField("ins_refund_cost", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.provisionalDue2supplier</code>.
     */
    public final TableField<ComputedvaluesRecord, BigDecimal> PROVISIONALDUE2SUPPLIER = createField("provisionalDue2supplier", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.computedValues.axa_inv</code>.
     */
    public final TableField<ComputedvaluesRecord, Boolean> AXA_INV = createField("axa_inv", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.computedValues</code> table reference
     */
    public Computedvalues() {
        this(DSL.name("computedValues"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.computedValues</code> table reference
     */
    public Computedvalues(String alias) {
        this(DSL.name(alias), COMPUTEDVALUES);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.computedValues</code> table reference
     */
    public Computedvalues(Name alias) {
        this(alias, COMPUTEDVALUES);
    }

    private Computedvalues(Name alias, Table<ComputedvaluesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Computedvalues(Name alias, Table<ComputedvaluesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Computedvalues(Table<O> child, ForeignKey<O, ComputedvaluesRecord> key) {
        super(child, key, COMPUTEDVALUES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COMPUTEDVALUES_PK_COMPUTEDVALUES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ComputedvaluesRecord> getPrimaryKey() {
        return Keys.PK_COMPUTEDVALUES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ComputedvaluesRecord>> getKeys() {
        return Arrays.<UniqueKey<ComputedvaluesRecord>>asList(Keys.PK_COMPUTEDVALUES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Computedvalues as(String alias) {
        return new Computedvalues(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Computedvalues as(Name alias) {
        return new Computedvalues(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Computedvalues rename(String name) {
        return new Computedvalues(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Computedvalues rename(Name name) {
        return new Computedvalues(name, null);
    }
}
