/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.Indexes;
import jooq.cartrawler_dev_internal.dbo.Keys;
import jooq.cartrawler_dev_internal.dbo.tables.records.DirgroupRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dirgroup extends TableImpl<DirgroupRecord> {

    private static final long serialVersionUID = 168408067;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.DirGroup</code>
     */
    public static final Dirgroup DIRGROUP = new Dirgroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DirgroupRecord> getRecordType() {
        return DirgroupRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.Group_ID</code>.
     */
    public final TableField<DirgroupRecord, String> GROUP_ID = createField("Group_ID", org.jooq.impl.SQLDataType.CHAR(2).nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.Description</code>.
     */
    public final TableField<DirgroupRecord, String> DESCRIPTION = createField("Description", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.Contents</code>.
     */
    public final TableField<DirgroupRecord, String> CONTENTS = createField("Contents", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.bgColor</code>.
     */
    public final TableField<DirgroupRecord, String> BGCOLOR = createField("bgColor", org.jooq.impl.SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.fontColor</code>.
     */
    public final TableField<DirgroupRecord, String> FONTCOLOR = createField("fontColor", org.jooq.impl.SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.Image_On</code>.
     */
    public final TableField<DirgroupRecord, String> IMAGE_ON = createField("Image_On", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.Image_Off</code>.
     */
    public final TableField<DirgroupRecord, String> IMAGE_OFF = createField("Image_Off", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.Top_Image</code>.
     */
    public final TableField<DirgroupRecord, String> TOP_IMAGE = createField("Top_Image", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.opening_image</code>.
     */
    public final TableField<DirgroupRecord, String> OPENING_IMAGE = createField("opening_image", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.DirGroup.opening_text</code>.
     */
    public final TableField<DirgroupRecord, String> OPENING_TEXT = createField("opening_text", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.DirGroup</code> table reference
     */
    public Dirgroup() {
        this(DSL.name("DirGroup"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.DirGroup</code> table reference
     */
    public Dirgroup(String alias) {
        this(DSL.name(alias), DIRGROUP);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.DirGroup</code> table reference
     */
    public Dirgroup(Name alias) {
        this(alias, DIRGROUP);
    }

    private Dirgroup(Name alias, Table<DirgroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private Dirgroup(Name alias, Table<DirgroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Dirgroup(Table<O> child, ForeignKey<O, DirgroupRecord> key) {
        super(child, key, DIRGROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DIRGROUP_PK_DIRGROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DirgroupRecord> getPrimaryKey() {
        return Keys.PK_DIRGROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DirgroupRecord>> getKeys() {
        return Arrays.<UniqueKey<DirgroupRecord>>asList(Keys.PK_DIRGROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Dirgroup as(String alias) {
        return new Dirgroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Dirgroup as(Name alias) {
        return new Dirgroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dirgroup rename(String name) {
        return new Dirgroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dirgroup rename(Name name) {
        return new Dirgroup(name, null);
    }
}
