/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.Indexes;
import jooq.cartrawler_dev_internal.dbo.Keys;
import jooq.cartrawler_dev_internal.dbo.tables.records.GroupRatesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupRates extends TableImpl<GroupRatesRecord> {

    private static final long serialVersionUID = -1009846202;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.Group_Rates</code>
     */
    public static final GroupRates GROUP_RATES = new GroupRates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupRatesRecord> getRecordType() {
        return GroupRatesRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.Group_Rates.Group_ID</code>.
     */
    public final TableField<GroupRatesRecord, String> GROUP_ID = createField("Group_ID", org.jooq.impl.SQLDataType.VARCHAR(6).nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.Group_Rates.Season_ID</code>.
     */
    public final TableField<GroupRatesRecord, String> SEASON_ID = createField("Season_ID", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.Group_Rates.Days_From</code>.
     */
    public final TableField<GroupRatesRecord, Integer> DAYS_FROM = createField("Days_From", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.Group_Rates.Days_To</code>.
     */
    public final TableField<GroupRatesRecord, Integer> DAYS_TO = createField("Days_To", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.Group_Rates.Rate</code>.
     */
    public final TableField<GroupRatesRecord, BigDecimal> RATE = createField("Rate", org.jooq.impl.SQLDataType.NUMERIC(10, 2).defaultValue(org.jooq.impl.DSL.field("((0))", org.jooq.impl.SQLDataType.NUMERIC)), this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.Group_Rates</code> table reference
     */
    public GroupRates() {
        this(DSL.name("Group_Rates"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.Group_Rates</code> table reference
     */
    public GroupRates(String alias) {
        this(DSL.name(alias), GROUP_RATES);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.Group_Rates</code> table reference
     */
    public GroupRates(Name alias) {
        this(alias, GROUP_RATES);
    }

    private GroupRates(Name alias, Table<GroupRatesRecord> aliased) {
        this(alias, aliased, null);
    }

    private GroupRates(Name alias, Table<GroupRatesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> GroupRates(Table<O> child, ForeignKey<O, GroupRatesRecord> key) {
        super(child, key, GROUP_RATES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GROUP_RATES_GROUP_RATES_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GroupRatesRecord> getPrimaryKey() {
        return Keys.GROUP_RATES_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GroupRatesRecord>> getKeys() {
        return Arrays.<UniqueKey<GroupRatesRecord>>asList(Keys.GROUP_RATES_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupRates as(String alias) {
        return new GroupRates(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupRates as(Name alias) {
        return new GroupRates(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupRates rename(String name) {
        return new GroupRates(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupRates rename(Name name) {
        return new GroupRates(name, null);
    }
}
