/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.Indexes;
import jooq.cartrawler_dev_internal.dbo.Keys;
import jooq.cartrawler_dev_internal.dbo.tables.records.HolidayautossuppliercodesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Holidayautossuppliercodes extends TableImpl<HolidayautossuppliercodesRecord> {

    private static final long serialVersionUID = 393358336;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.HolidayAutosSupplierCodes</code>
     */
    public static final Holidayautossuppliercodes HOLIDAYAUTOSSUPPLIERCODES = new Holidayautossuppliercodes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HolidayautossuppliercodesRecord> getRecordType() {
        return HolidayautossuppliercodesRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.HolidayAutosSupplierCodes.guid</code>.
     */
    public final TableField<HolidayautossuppliercodesRecord, UUID> GUID = createField("guid", org.jooq.impl.SQLDataType.UUID.nullable(false).defaultValue(org.jooq.impl.DSL.field("(newid())", org.jooq.impl.SQLDataType.UUID)), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.HolidayAutosSupplierCodes.code</code>.
     */
    public final TableField<HolidayautossuppliercodesRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.HolidayAutosSupplierCodes.name</code>.
     */
    public final TableField<HolidayautossuppliercodesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.HolidayAutosSupplierCodes.supplier</code>.
     */
    public final TableField<HolidayautossuppliercodesRecord, String> SUPPLIER = createField("supplier", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.HolidayAutosSupplierCodes</code> table reference
     */
    public Holidayautossuppliercodes() {
        this(DSL.name("HolidayAutosSupplierCodes"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.HolidayAutosSupplierCodes</code> table reference
     */
    public Holidayautossuppliercodes(String alias) {
        this(DSL.name(alias), HOLIDAYAUTOSSUPPLIERCODES);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.HolidayAutosSupplierCodes</code> table reference
     */
    public Holidayautossuppliercodes(Name alias) {
        this(alias, HOLIDAYAUTOSSUPPLIERCODES);
    }

    private Holidayautossuppliercodes(Name alias, Table<HolidayautossuppliercodesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Holidayautossuppliercodes(Name alias, Table<HolidayautossuppliercodesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Holidayautossuppliercodes(Table<O> child, ForeignKey<O, HolidayautossuppliercodesRecord> key) {
        super(child, key, HOLIDAYAUTOSSUPPLIERCODES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HOLIDAYAUTOSSUPPLIERCODES_PK_HOLIDAYAUTOSSUPPLIERCODES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<HolidayautossuppliercodesRecord> getPrimaryKey() {
        return Keys.PK_HOLIDAYAUTOSSUPPLIERCODES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HolidayautossuppliercodesRecord>> getKeys() {
        return Arrays.<UniqueKey<HolidayautossuppliercodesRecord>>asList(Keys.PK_HOLIDAYAUTOSSUPPLIERCODES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Holidayautossuppliercodes as(String alias) {
        return new Holidayautossuppliercodes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Holidayautossuppliercodes as(Name alias) {
        return new Holidayautossuppliercodes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Holidayautossuppliercodes rename(String name) {
        return new Holidayautossuppliercodes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Holidayautossuppliercodes rename(Name name) {
        return new Holidayautossuppliercodes(name, null);
    }
}
