/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.Indexes;
import jooq.cartrawler_dev_internal.dbo.Keys;
import jooq.cartrawler_dev_internal.dbo.tables.records.IssclientListRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IssclientList extends TableImpl<IssclientListRecord> {

    private static final long serialVersionUID = -685007597;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.issClient_list</code>
     */
    public static final IssclientList ISSCLIENT_LIST = new IssclientList();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IssclientListRecord> getRecordType() {
        return IssclientListRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.issClient_list.client_Id</code>.
     */
    public final TableField<IssclientListRecord, Integer> CLIENT_ID = createField("client_Id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.issClient_list.client_group_id</code>.
     */
    public final TableField<IssclientListRecord, Integer> CLIENT_GROUP_ID = createField("client_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.issClient_list</code> table reference
     */
    public IssclientList() {
        this(DSL.name("issClient_list"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.issClient_list</code> table reference
     */
    public IssclientList(String alias) {
        this(DSL.name(alias), ISSCLIENT_LIST);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.issClient_list</code> table reference
     */
    public IssclientList(Name alias) {
        this(alias, ISSCLIENT_LIST);
    }

    private IssclientList(Name alias, Table<IssclientListRecord> aliased) {
        this(alias, aliased, null);
    }

    private IssclientList(Name alias, Table<IssclientListRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> IssclientList(Table<O> child, ForeignKey<O, IssclientListRecord> key) {
        super(child, key, ISSCLIENT_LIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ISSCLIENT_LIST_PK_ISSCLIENT_LIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IssclientListRecord> getPrimaryKey() {
        return Keys.PK_ISSCLIENT_LIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IssclientListRecord>> getKeys() {
        return Arrays.<UniqueKey<IssclientListRecord>>asList(Keys.PK_ISSCLIENT_LIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<IssclientListRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<IssclientListRecord, ?>>asList(Keys.FK_ISSCLIENT_LIST_CLIENT_GROUP_ID);
    }

    public IssclientGroup issclientGroup() {
        return new IssclientGroup(this, Keys.FK_ISSCLIENT_LIST_CLIENT_GROUP_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssclientList as(String alias) {
        return new IssclientList(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssclientList as(Name alias) {
        return new IssclientList(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IssclientList rename(String name) {
        return new IssclientList(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IssclientList rename(Name name) {
        return new IssclientList(name, null);
    }
}
