/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.Keys;
import jooq.cartrawler_dev_internal.dbo.tables.records.OptimizationElasticityAdjustmentsBakRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptimizationElasticityAdjustmentsBak extends TableImpl<OptimizationElasticityAdjustmentsBakRecord> {

    private static final long serialVersionUID = -1997611090;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak</code>
     */
    public static final OptimizationElasticityAdjustmentsBak OPTIMIZATION_ELASTICITY_ADJUSTMENTS_BAK = new OptimizationElasticityAdjustmentsBak();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OptimizationElasticityAdjustmentsBakRecord> getRecordType() {
        return OptimizationElasticityAdjustmentsBakRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.id</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.channel_group</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> CHANNEL_GROUP = createField("channel_group", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.channel_corridor</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, String> CHANNEL_CORRIDOR = createField("channel_corridor", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.fk_channel</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> FK_CHANNEL = createField("fk_channel", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.adjustment_final</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, BigDecimal> ADJUSTMENT_FINAL = createField("adjustment_final", org.jooq.impl.SQLDataType.NUMERIC(12, 9).nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.fk_client</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> FK_CLIENT = createField("fk_client", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.adjustment_final_test</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, BigDecimal> ADJUSTMENT_FINAL_TEST = createField("adjustment_final_test", org.jooq.impl.SQLDataType.NUMERIC(12, 9), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.origin_country</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, String> ORIGIN_COUNTRY = createField("origin_country", org.jooq.impl.SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.destination_country</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, String> DESTINATION_COUNTRY = createField("destination_country", org.jooq.impl.SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.Location_id</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> LOCATION_ID = createField("Location_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.car_type</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> CAR_TYPE = createField("car_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.transition_flag</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> TRANSITION_FLAG = createField("transition_flag", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.Amended_by</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> AMENDED_BY = createField("Amended_by", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.Amend_date</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Timestamp> AMEND_DATE = createField("Amend_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.min_rental_duration</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> MIN_RENTAL_DURATION = createField("min_rental_duration", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.max_rental_duration</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> MAX_RENTAL_DURATION = createField("max_rental_duration", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.min_pickup_lead</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> MIN_PICKUP_LEAD = createField("min_pickup_lead", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak.max_pickup_lead</code>.
     */
    public final TableField<OptimizationElasticityAdjustmentsBakRecord, Integer> MAX_PICKUP_LEAD = createField("max_pickup_lead", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak</code> table reference
     */
    public OptimizationElasticityAdjustmentsBak() {
        this(DSL.name("optimization_elasticity_adjustments_bak"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak</code> table reference
     */
    public OptimizationElasticityAdjustmentsBak(String alias) {
        this(DSL.name(alias), OPTIMIZATION_ELASTICITY_ADJUSTMENTS_BAK);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments_bak</code> table reference
     */
    public OptimizationElasticityAdjustmentsBak(Name alias) {
        this(alias, OPTIMIZATION_ELASTICITY_ADJUSTMENTS_BAK);
    }

    private OptimizationElasticityAdjustmentsBak(Name alias, Table<OptimizationElasticityAdjustmentsBakRecord> aliased) {
        this(alias, aliased, null);
    }

    private OptimizationElasticityAdjustmentsBak(Name alias, Table<OptimizationElasticityAdjustmentsBakRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OptimizationElasticityAdjustmentsBak(Table<O> child, ForeignKey<O, OptimizationElasticityAdjustmentsBakRecord> key) {
        super(child, key, OPTIMIZATION_ELASTICITY_ADJUSTMENTS_BAK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OptimizationElasticityAdjustmentsBakRecord, Integer> getIdentity() {
        return Keys.IDENTITY_OPTIMIZATION_ELASTICITY_ADJUSTMENTS_BAK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsBak as(String alias) {
        return new OptimizationElasticityAdjustmentsBak(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsBak as(Name alias) {
        return new OptimizationElasticityAdjustmentsBak(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OptimizationElasticityAdjustmentsBak rename(String name) {
        return new OptimizationElasticityAdjustmentsBak(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OptimizationElasticityAdjustmentsBak rename(Name name) {
        return new OptimizationElasticityAdjustmentsBak(name, null);
    }
}
