/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.Indexes;
import jooq.cartrawler_dev_internal.dbo.Keys;
import jooq.cartrawler_dev_internal.dbo.tables.records.ReservationSplitChargesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReservationSplitCharges extends TableImpl<ReservationSplitChargesRecord> {

    private static final long serialVersionUID = -83076253;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.Reservation_Split_Charges</code>
     */
    public static final ReservationSplitCharges RESERVATION_SPLIT_CHARGES = new ReservationSplitCharges();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReservationSplitChargesRecord> getRecordType() {
        return ReservationSplitChargesRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.Reservation_Split_Charges.Ref</code>.
     */
    public final TableField<ReservationSplitChargesRecord, Integer> REF = createField("Ref", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.Reservation_Split_Charges.oneway_charge</code>.
     */
    public final TableField<ReservationSplitChargesRecord, BigDecimal> ONEWAY_CHARGE = createField("oneway_charge", org.jooq.impl.SQLDataType.NUMERIC(9, 3), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.Reservation_Split_Charges.daterange_charge</code>.
     */
    public final TableField<ReservationSplitChargesRecord, BigDecimal> DATERANGE_CHARGE = createField("daterange_charge", org.jooq.impl.SQLDataType.NUMERIC(9, 3), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.Reservation_Split_Charges.channelPricingMarkup</code>.
     */
    public final TableField<ReservationSplitChargesRecord, BigDecimal> CHANNELPRICINGMARKUP = createField("channelPricingMarkup", org.jooq.impl.SQLDataType.NUMERIC(19, 4), this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.Reservation_Split_Charges</code> table reference
     */
    public ReservationSplitCharges() {
        this(DSL.name("Reservation_Split_Charges"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.Reservation_Split_Charges</code> table reference
     */
    public ReservationSplitCharges(String alias) {
        this(DSL.name(alias), RESERVATION_SPLIT_CHARGES);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.Reservation_Split_Charges</code> table reference
     */
    public ReservationSplitCharges(Name alias) {
        this(alias, RESERVATION_SPLIT_CHARGES);
    }

    private ReservationSplitCharges(Name alias, Table<ReservationSplitChargesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReservationSplitCharges(Name alias, Table<ReservationSplitChargesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ReservationSplitCharges(Table<O> child, ForeignKey<O, ReservationSplitChargesRecord> key) {
        super(child, key, RESERVATION_SPLIT_CHARGES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RESERVATION_SPLIT_CHARGES_PK_RESERVATION_SPLIT_CHARGES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReservationSplitChargesRecord> getPrimaryKey() {
        return Keys.PK_RESERVATION_SPLIT_CHARGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReservationSplitChargesRecord>> getKeys() {
        return Arrays.<UniqueKey<ReservationSplitChargesRecord>>asList(Keys.PK_RESERVATION_SPLIT_CHARGES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationSplitCharges as(String alias) {
        return new ReservationSplitCharges(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationSplitCharges as(Name alias) {
        return new ReservationSplitCharges(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReservationSplitCharges rename(String name) {
        return new ReservationSplitCharges(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReservationSplitCharges rename(Name name) {
        return new ReservationSplitCharges(name, null);
    }
}
