/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.math.BigDecimal;
import java.util.UUID;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.tables.records.RuleChargeBak20170913Record;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RuleChargeBak20170913 extends TableImpl<RuleChargeBak20170913Record> {

    private static final long serialVersionUID = -1496928361;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913</code>
     */
    public static final RuleChargeBak20170913 RULE_CHARGE_BAK20170913 = new RuleChargeBak20170913();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RuleChargeBak20170913Record> getRecordType() {
        return RuleChargeBak20170913Record.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.guid</code>.
     */
    public final TableField<RuleChargeBak20170913Record, UUID> GUID = createField("guid", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.rule_charge_id</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Integer> RULE_CHARGE_ID = createField("rule_charge_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.unit</code>.
     */
    public final TableField<RuleChargeBak20170913Record, String> UNIT = createField("unit", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.unit_amount</code>.
     */
    public final TableField<RuleChargeBak20170913Record, BigDecimal> UNIT_AMOUNT = createField("unit_amount", org.jooq.impl.SQLDataType.NUMERIC(19, 6), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.base_amount</code>.
     */
    public final TableField<RuleChargeBak20170913Record, BigDecimal> BASE_AMOUNT = createField("base_amount", org.jooq.impl.SQLDataType.NUMERIC(19, 6), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.min_amount</code>.
     */
    public final TableField<RuleChargeBak20170913Record, BigDecimal> MIN_AMOUNT = createField("min_amount", org.jooq.impl.SQLDataType.NUMERIC(19, 6), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.max_amount</code>.
     */
    public final TableField<RuleChargeBak20170913Record, BigDecimal> MAX_AMOUNT = createField("max_amount", org.jooq.impl.SQLDataType.NUMERIC(19, 6), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.min_units</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Integer> MIN_UNITS = createField("min_units", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.max_units</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Integer> MAX_UNITS = createField("max_units", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.percentage</code>.
     */
    public final TableField<RuleChargeBak20170913Record, BigDecimal> PERCENTAGE = createField("percentage", org.jooq.impl.SQLDataType.NUMERIC(19, 6), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.currency</code>.
     */
    public final TableField<RuleChargeBak20170913Record, String> CURRENCY = createField("currency", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.in_rate</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Boolean> IN_RATE = createField("in_rate", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.tax_exclusive</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Boolean> TAX_EXCLUSIVE = createField("tax_exclusive", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.on_request</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Boolean> ON_REQUEST = createField("on_request", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.excess</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Boolean> EXCESS = createField("excess", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.excess_amount</code>.
     */
    public final TableField<RuleChargeBak20170913Record, BigDecimal> EXCESS_AMOUNT = createField("excess_amount", org.jooq.impl.SQLDataType.NUMERIC(19, 6), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.monthday_period</code>.
     */
    public final TableField<RuleChargeBak20170913Record, String> MONTHDAY_PERIOD = createField("monthday_period", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.payable_at_counter</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Boolean> PAYABLE_AT_COUNTER = createField("payable_at_counter", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.required</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Boolean> REQUIRED = createField("required", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.rate_type</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Integer> RATE_TYPE = createField("rate_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.max_coverage</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Boolean> MAX_COVERAGE = createField("max_coverage", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.max_coverage_unlimited</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Boolean> MAX_COVERAGE_UNLIMITED = createField("max_coverage_unlimited", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.max_coverage_amount</code>.
     */
    public final TableField<RuleChargeBak20170913Record, BigDecimal> MAX_COVERAGE_AMOUNT = createField("max_coverage_amount", org.jooq.impl.SQLDataType.NUMERIC(19, 6), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.deposit_amount</code>.
     */
    public final TableField<RuleChargeBak20170913Record, BigDecimal> DEPOSIT_AMOUNT = createField("deposit_amount", org.jooq.impl.SQLDataType.NUMERIC(19, 6), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913.deposit</code>.
     */
    public final TableField<RuleChargeBak20170913Record, Boolean> DEPOSIT = createField("deposit", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913</code> table reference
     */
    public RuleChargeBak20170913() {
        this(DSL.name("rule_charge_bak20170913"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913</code> table reference
     */
    public RuleChargeBak20170913(String alias) {
        this(DSL.name(alias), RULE_CHARGE_BAK20170913);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.rule_charge_bak20170913</code> table reference
     */
    public RuleChargeBak20170913(Name alias) {
        this(alias, RULE_CHARGE_BAK20170913);
    }

    private RuleChargeBak20170913(Name alias, Table<RuleChargeBak20170913Record> aliased) {
        this(alias, aliased, null);
    }

    private RuleChargeBak20170913(Name alias, Table<RuleChargeBak20170913Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RuleChargeBak20170913(Table<O> child, ForeignKey<O, RuleChargeBak20170913Record> key) {
        super(child, key, RULE_CHARGE_BAK20170913);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleChargeBak20170913 as(String alias) {
        return new RuleChargeBak20170913(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleChargeBak20170913 as(Name alias) {
        return new RuleChargeBak20170913(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RuleChargeBak20170913 rename(String name) {
        return new RuleChargeBak20170913(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RuleChargeBak20170913 rename(Name name) {
        return new RuleChargeBak20170913(name, null);
    }
}
