/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.tables.records.UserGroupRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroup extends TableImpl<UserGroupRecord> {

    private static final long serialVersionUID = -702940965;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.user_group</code>
     */
    public static final UserGroup USER_GROUP = new UserGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserGroupRecord> getRecordType() {
        return UserGroupRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.user_group.clientId</code>.
     */
    public final TableField<UserGroupRecord, Integer> CLIENTID = createField("clientId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.user_group.userGroup</code>.
     */
    public final TableField<UserGroupRecord, String> USERGROUP = createField("userGroup", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.user_group.financeChannel</code>.
     */
    public final TableField<UserGroupRecord, String> FINANCECHANNEL = createField("financeChannel", org.jooq.impl.SQLDataType.VARCHAR(27).nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.user_group.financeChannel2</code>.
     */
    public final TableField<UserGroupRecord, String> FINANCECHANNEL2 = createField("financeChannel2", org.jooq.impl.SQLDataType.VARCHAR(27), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.user_group.experimentGroup</code>.
     */
    public final TableField<UserGroupRecord, String> EXPERIMENTGROUP = createField("experimentGroup", org.jooq.impl.SQLDataType.VARCHAR(8000), this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.user_group</code> table reference
     */
    public UserGroup() {
        this(DSL.name("user_group"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.user_group</code> table reference
     */
    public UserGroup(String alias) {
        this(DSL.name(alias), USER_GROUP);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.user_group</code> table reference
     */
    public UserGroup(Name alias) {
        this(alias, USER_GROUP);
    }

    private UserGroup(Name alias, Table<UserGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserGroup(Name alias, Table<UserGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserGroup(Table<O> child, ForeignKey<O, UserGroupRecord> key) {
        super(child, key, USER_GROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroup as(String alias) {
        return new UserGroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroup as(Name alias) {
        return new UserGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserGroup rename(String name) {
        return new UserGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserGroup rename(Name name) {
        return new UserGroup(name, null);
    }
}
