/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.tables.records.ViewResGroupCarRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewResGroupCar extends TableImpl<ViewResGroupCarRecord> {

    private static final long serialVersionUID = -46598731;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.view_res_group_car</code>
     */
    public static final ViewResGroupCar VIEW_RES_GROUP_CAR = new ViewResGroupCar();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewResGroupCarRecord> getRecordType() {
        return ViewResGroupCarRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.res_group_code</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> RES_GROUP_CODE = createField("res_group_code", org.jooq.impl.SQLDataType.CHAR(4).nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.region_id</code>.
     */
    public final TableField<ViewResGroupCarRecord, UByte> REGION_ID = createField("region_id", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.sample_car_id</code>.
     */
    public final TableField<ViewResGroupCarRecord, Integer> SAMPLE_CAR_ID = createField("sample_car_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.automatic</code>.
     */
    public final TableField<ViewResGroupCarRecord, Boolean> AUTOMATIC = createField("automatic", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.aircon</code>.
     */
    public final TableField<ViewResGroupCarRecord, Boolean> AIRCON = createField("aircon", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.gps</code>.
     */
    public final TableField<ViewResGroupCarRecord, Boolean> GPS = createField("gps", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.bags</code>.
     */
    public final TableField<ViewResGroupCarRecord, UByte> BAGS = createField("bags", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.paslarge</code>.
     */
    public final TableField<ViewResGroupCarRecord, UByte> PASLARGE = createField("paslarge", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.passmall</code>.
     */
    public final TableField<ViewResGroupCarRecord, UByte> PASSMALL = createField("passmall", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.doors</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> DOORS = createField("doors", org.jooq.impl.SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.seats</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> SEATS = createField("seats", org.jooq.impl.SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.drive</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> DRIVE = createField("drive", org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.fuel</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> FUEL = createField("fuel", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.ota_vehicle_category</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> OTA_VEHICLE_CATEGORY = createField("ota_vehicle_category", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.ota_vehicle_class_size</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> OTA_VEHICLE_CLASS_SIZE = createField("ota_vehicle_class_size", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.enginesize</code>.
     */
    public final TableField<ViewResGroupCarRecord, Double> ENGINESIZE = createField("enginesize", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.fuelconsumption</code>.
     */
    public final TableField<ViewResGroupCarRecord, Double> FUELCONSUMPTION = createField("fuelconsumption", org.jooq.impl.SQLDataType.FLOAT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.fuelconsumption_unit</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> FUELCONSUMPTION_UNIT = createField("fuelconsumption_unit", org.jooq.impl.SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.picture</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> PICTURE = createField("picture", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.picture_plain</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> PICTURE_PLAIN = createField("picture_plain", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.ranking</code>.
     */
    public final TableField<ViewResGroupCarRecord, UByte> RANKING = createField("ranking", org.jooq.impl.SQLDataType.TINYINTUNSIGNED, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.cartrawler_category</code>.
     */
    public final TableField<ViewResGroupCarRecord, Short> CARTRAWLER_CATEGORY = createField("cartrawler_category", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.country_id</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.car_id</code>.
     */
    public final TableField<ViewResGroupCarRecord, Integer> CAR_ID = createField("car_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.make</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> MAKE = createField("make", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.model</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> MODEL = createField("model", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.view_res_group_car.description</code>.
     */
    public final TableField<ViewResGroupCarRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.view_res_group_car</code> table reference
     */
    public ViewResGroupCar() {
        this(DSL.name("view_res_group_car"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.view_res_group_car</code> table reference
     */
    public ViewResGroupCar(String alias) {
        this(DSL.name(alias), VIEW_RES_GROUP_CAR);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.view_res_group_car</code> table reference
     */
    public ViewResGroupCar(Name alias) {
        this(alias, VIEW_RES_GROUP_CAR);
    }

    private ViewResGroupCar(Name alias, Table<ViewResGroupCarRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewResGroupCar(Name alias, Table<ViewResGroupCarRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ViewResGroupCar(Table<O> child, ForeignKey<O, ViewResGroupCarRecord> key) {
        super(child, key, VIEW_RES_GROUP_CAR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewResGroupCar as(String alias) {
        return new ViewResGroupCar(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewResGroupCar as(Name alias) {
        return new ViewResGroupCar(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewResGroupCar rename(String name) {
        return new ViewResGroupCar(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewResGroupCar rename(Name name) {
        return new ViewResGroupCar(name, null);
    }
}
