/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.Dbo;
import jooq.cartrawler_dev_internal.dbo.Indexes;
import jooq.cartrawler_dev_internal.dbo.Keys;
import jooq.cartrawler_dev_internal.dbo.tables.records.XmlAgentRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class XmlAgent extends TableImpl<XmlAgentRecord> {

    private static final long serialVersionUID = 1767652823;

    /**
     * The reference instance of <code>Cartrawler_dev_internal.dbo.XML_Agent</code>
     */
    public static final XmlAgent XML_AGENT = new XmlAgent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<XmlAgentRecord> getRecordType() {
        return XmlAgentRecord.class;
    }

    /**
     * The column <code>Cartrawler_dev_internal.dbo.XML_Agent.XML_Agent_ID</code>.
     */
    public final TableField<XmlAgentRecord, Integer> XML_AGENT_ID = createField("XML_Agent_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.XML_Agent.XML_Agent_Name</code>.
     */
    public final TableField<XmlAgentRecord, String> XML_AGENT_NAME = createField("XML_Agent_Name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.XML_Agent.Argus_Contact_Name</code>.
     */
    public final TableField<XmlAgentRecord, String> ARGUS_CONTACT_NAME = createField("Argus_Contact_Name", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.XML_Agent.Argus_Contact_Phone</code>.
     */
    public final TableField<XmlAgentRecord, String> ARGUS_CONTACT_PHONE = createField("Argus_Contact_Phone", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.XML_Agent.Argus_Contact_Email</code>.
     */
    public final TableField<XmlAgentRecord, String> ARGUS_CONTACT_EMAIL = createField("Argus_Contact_Email", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.XML_Agent.Rate_Difference</code>.
     */
    public final TableField<XmlAgentRecord, BigDecimal> RATE_DIFFERENCE = createField("Rate_Difference", org.jooq.impl.SQLDataType.NUMERIC(9, 2), this, "");

    /**
     * The column <code>Cartrawler_dev_internal.dbo.XML_Agent.XML_Agent_Status</code>.
     */
    public final TableField<XmlAgentRecord, Boolean> XML_AGENT_STATUS = createField("XML_Agent_Status", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * Create a <code>Cartrawler_dev_internal.dbo.XML_Agent</code> table reference
     */
    public XmlAgent() {
        this(DSL.name("XML_Agent"), null);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.XML_Agent</code> table reference
     */
    public XmlAgent(String alias) {
        this(DSL.name(alias), XML_AGENT);
    }

    /**
     * Create an aliased <code>Cartrawler_dev_internal.dbo.XML_Agent</code> table reference
     */
    public XmlAgent(Name alias) {
        this(alias, XML_AGENT);
    }

    private XmlAgent(Name alias, Table<XmlAgentRecord> aliased) {
        this(alias, aliased, null);
    }

    private XmlAgent(Name alias, Table<XmlAgentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> XmlAgent(Table<O> child, ForeignKey<O, XmlAgentRecord> key) {
        super(child, key, XML_AGENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dbo.DBO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.XML_AGENT_PK_XML_AGENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<XmlAgentRecord, Integer> getIdentity() {
        return Keys.IDENTITY_XML_AGENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<XmlAgentRecord> getPrimaryKey() {
        return Keys.PK_XML_AGENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<XmlAgentRecord>> getKeys() {
        return Arrays.<UniqueKey<XmlAgentRecord>>asList(Keys.PK_XML_AGENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XmlAgent as(String alias) {
        return new XmlAgent(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public XmlAgent as(Name alias) {
        return new XmlAgent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public XmlAgent rename(String name) {
        return new XmlAgent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public XmlAgent rename(Name name) {
        return new XmlAgent(name, null);
    }
}
