/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import java.util.UUID;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.Arcmemocounter;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArcmemocounterRecord extends UpdatableRecordImpl<ArcmemocounterRecord> implements Record3<UUID, Long, Long> {

    private static final long serialVersionUID = 531580924;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.ARCMEMOCOUNTER.guid</code>.
     */
    public void setGuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.ARCMEMOCOUNTER.guid</code>.
     */
    public UUID getGuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.ARCMEMOCOUNTER.LASTMEMO</code>.
     */
    public void setLastmemo(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.ARCMEMOCOUNTER.LASTMEMO</code>.
     */
    public Long getLastmemo() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.ARCMEMOCOUNTER.LASTCREDITMEMO</code>.
     */
    public void setLastcreditmemo(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.ARCMEMOCOUNTER.LASTCREDITMEMO</code>.
     */
    public Long getLastcreditmemo() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UUID, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UUID, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Arcmemocounter.ARCMEMOCOUNTER.GUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Arcmemocounter.ARCMEMOCOUNTER.LASTMEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Arcmemocounter.ARCMEMOCOUNTER.LASTCREDITMEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getLastmemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getLastcreditmemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getLastmemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getLastcreditmemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArcmemocounterRecord value1(UUID value) {
        setGuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArcmemocounterRecord value2(Long value) {
        setLastmemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArcmemocounterRecord value3(Long value) {
        setLastcreditmemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArcmemocounterRecord values(UUID value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArcmemocounterRecord
     */
    public ArcmemocounterRecord() {
        super(Arcmemocounter.ARCMEMOCOUNTER);
    }

    /**
     * Create a detached, initialised ArcmemocounterRecord
     */
    public ArcmemocounterRecord(UUID guid, Long lastmemo, Long lastcreditmemo) {
        super(Arcmemocounter.ARCMEMOCOUNTER);

        set(0, guid);
        set(1, lastmemo);
        set(2, lastcreditmemo);
    }
}
