/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.ClientPlan;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientPlanRecord extends UpdatableRecordImpl<ClientPlanRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 750909091;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Client_Plan.Plan_ID</code>.
     */
    public void setPlanId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Client_Plan.Plan_ID</code>.
     */
    public Integer getPlanId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Client_Plan.Plan_Name</code>.
     */
    public void setPlanName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Client_Plan.Plan_Name</code>.
     */
    public String getPlanName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ClientPlan.CLIENT_PLAN.PLAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ClientPlan.CLIENT_PLAN.PLAN_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPlanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPlanName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPlanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPlanName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientPlanRecord value1(Integer value) {
        setPlanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientPlanRecord value2(String value) {
        setPlanName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClientPlanRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientPlanRecord
     */
    public ClientPlanRecord() {
        super(ClientPlan.CLIENT_PLAN);
    }

    /**
     * Create a detached, initialised ClientPlanRecord
     */
    public ClientPlanRecord(Integer planId, String planName) {
        super(ClientPlan.CLIENT_PLAN);

        set(0, planId);
        set(1, planName);
    }
}
