/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.Continents;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContinentsRecord extends UpdatableRecordImpl<ContinentsRecord> implements Record11<Integer, String, String, String, String, String, byte[], String, String, Boolean, String> {

    private static final long serialVersionUID = 1150507638;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Id</code>.
     */
    public void setContinentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Id</code>.
     */
    public Integer getContinentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Name</code>.
     */
    public void setContinentName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Name</code>.
     */
    public String getContinentName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Text</code>.
     */
    public void setContinentText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Text</code>.
     */
    public String getContinentText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Page_Title</code>.
     */
    public void setPageTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Page_Title</code>.
     */
    public String getPageTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Meta_Description</code>.
     */
    public void setMetaDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Meta_Description</code>.
     */
    public String getMetaDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Meta_Keywords</code>.
     */
    public void setMetaKeywords(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Meta_Keywords</code>.
     */
    public String getMetaKeywords() {
        return (String) get(5);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Image</code>.
     */
    public void setContinentImage(byte... value) {
        set(6, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Image</code>.
     */
    public byte[] getContinentImage() {
        return (byte[]) get(6);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Image_Width</code>.
     */
    public void setImageWidth(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Image_Width</code>.
     */
    public String getImageWidth() {
        return (String) get(7);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Image_Height</code>.
     */
    public void setImageHeight(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Image_Height</code>.
     */
    public String getImageHeight() {
        return (String) get(8);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Updated</code>.
     */
    public void setUpdated(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Updated</code>.
     */
    public Boolean getUpdated() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Map</code>.
     */
    public void setContinentMap(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Continents.Continent_Map</code>.
     */
    public String getContinentMap() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, byte[], String, String, Boolean, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, String, String, byte[], String, String, Boolean, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Continents.CONTINENTS.CONTINENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Continents.CONTINENTS.CONTINENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Continents.CONTINENTS.CONTINENT_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Continents.CONTINENTS.PAGE_TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Continents.CONTINENTS.META_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Continents.CONTINENTS.META_KEYWORDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field7() {
        return Continents.CONTINENTS.CONTINENT_IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Continents.CONTINENTS.IMAGE_WIDTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Continents.CONTINENTS.IMAGE_HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return Continents.CONTINENTS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Continents.CONTINENTS.CONTINENT_MAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getContinentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getContinentName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContinentText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPageTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMetaDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMetaKeywords();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component7() {
        return getContinentImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getImageWidth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getImageHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getContinentMap();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getContinentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContinentName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContinentText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPageTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMetaDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMetaKeywords();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value7() {
        return getContinentImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getImageWidth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getImageHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getContinentMap();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value1(Integer value) {
        setContinentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value2(String value) {
        setContinentName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value3(String value) {
        setContinentText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value4(String value) {
        setPageTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value5(String value) {
        setMetaDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value6(String value) {
        setMetaKeywords(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value7(byte... value) {
        setContinentImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value8(String value) {
        setImageWidth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value9(String value) {
        setImageHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value10(Boolean value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord value11(String value) {
        setContinentMap(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContinentsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, byte[] value7, String value8, String value9, Boolean value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContinentsRecord
     */
    public ContinentsRecord() {
        super(Continents.CONTINENTS);
    }

    /**
     * Create a detached, initialised ContinentsRecord
     */
    public ContinentsRecord(Integer continentId, String continentName, String continentText, String pageTitle, String metaDescription, String metaKeywords, byte[] continentImage, String imageWidth, String imageHeight, Boolean updated, String continentMap) {
        super(Continents.CONTINENTS);

        set(0, continentId);
        set(1, continentName);
        set(2, continentText);
        set(3, pageTitle);
        set(4, metaDescription);
        set(5, metaKeywords);
        set(6, continentImage);
        set(7, imageWidth);
        set(8, imageHeight);
        set(9, updated);
        set(10, continentMap);
    }
}
