/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.EmailCompt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailComptRecord extends UpdatableRecordImpl<EmailComptRecord> implements Record6<String, String, String, String, String, String> {

    private static final long serialVersionUID = -1105456799;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Email_Add</code>.
     */
    public void setEmailAdd(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Email_Add</code>.
     */
    public String getEmailAdd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Country</code>.
     */
    public void setCountry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Ans_Website</code>.
     */
    public void setAnsWebsite(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Ans_Website</code>.
     */
    public String getAnsWebsite() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Ans_No_of_locations</code>.
     */
    public void setAnsNoOfLocations(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Ans_No_of_locations</code>.
     */
    public String getAnsNoOfLocations() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Ans_top_destination</code>.
     */
    public void setAnsTopDestination(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Email_Compt.Ans_top_destination</code>.
     */
    public String getAnsTopDestination() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return EmailCompt.EMAIL_COMPT.EMAIL_ADD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return EmailCompt.EMAIL_COMPT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return EmailCompt.EMAIL_COMPT.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return EmailCompt.EMAIL_COMPT.ANS_WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return EmailCompt.EMAIL_COMPT.ANS_NO_OF_LOCATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return EmailCompt.EMAIL_COMPT.ANS_TOP_DESTINATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getEmailAdd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAnsWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAnsNoOfLocations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAnsTopDestination();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEmailAdd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAnsWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAnsNoOfLocations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAnsTopDestination();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailComptRecord value1(String value) {
        setEmailAdd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailComptRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailComptRecord value3(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailComptRecord value4(String value) {
        setAnsWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailComptRecord value5(String value) {
        setAnsNoOfLocations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailComptRecord value6(String value) {
        setAnsTopDestination(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailComptRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailComptRecord
     */
    public EmailComptRecord() {
        super(EmailCompt.EMAIL_COMPT);
    }

    /**
     * Create a detached, initialised EmailComptRecord
     */
    public EmailComptRecord(String emailAdd, String name, String country, String ansWebsite, String ansNoOfLocations, String ansTopDestination) {
        super(EmailCompt.EMAIL_COMPT);

        set(0, emailAdd);
        set(1, name);
        set(2, country);
        set(3, ansWebsite);
        set(4, ansNoOfLocations);
        set(5, ansTopDestination);
    }
}
