/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.IssclientGroup;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IssclientGroupRecord extends UpdatableRecordImpl<IssclientGroupRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 188889185;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.issClient_Group.client_group_id</code>.
     */
    public void setClientGroupId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.issClient_Group.client_group_id</code>.
     */
    public Integer getClientGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.issClient_Group.client_group_name</code>.
     */
    public void setClientGroupName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.issClient_Group.client_group_name</code>.
     */
    public String getClientGroupName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return IssclientGroup.ISSCLIENT_GROUP.CLIENT_GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return IssclientGroup.ISSCLIENT_GROUP.CLIENT_GROUP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getClientGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getClientGroupName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getClientGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClientGroupName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssclientGroupRecord value1(Integer value) {
        setClientGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssclientGroupRecord value2(String value) {
        setClientGroupName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IssclientGroupRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IssclientGroupRecord
     */
    public IssclientGroupRecord() {
        super(IssclientGroup.ISSCLIENT_GROUP);
    }

    /**
     * Create a detached, initialised IssclientGroupRecord
     */
    public IssclientGroupRecord(Integer clientGroupId, String clientGroupName) {
        super(IssclientGroup.ISSCLIENT_GROUP);

        set(0, clientGroupId);
        set(1, clientGroupName);
    }
}
