/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.Location;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationRecord extends UpdatableRecordImpl<LocationRecord> {

    private static final long serialVersionUID = 378308202;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Location_ID</code>.
     */
    public void setLocationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Location_ID</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Agency_ID</code>.
     */
    public void setAgencyId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Agency_ID</code>.
     */
    public Integer getAgencyId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Location_Name</code>.
     */
    public void setLocationName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Location_Name</code>.
     */
    public String getLocationName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.display_order</code>.
     */
    public void setDisplayOrder(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.display_order</code>.
     */
    public Long getDisplayOrder() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Location_Address</code>.
     */
    public void setLocationAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Location_Address</code>.
     */
    public String getLocationAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Country_ID</code>.
     */
    public void setCountryId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Country_ID</code>.
     */
    public String getCountryId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.location_email</code>.
     */
    public void setLocationEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.location_email</code>.
     */
    public String getLocationEmail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Phone</code>.
     */
    public void setPhone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Phone</code>.
     */
    public String getPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Fax</code>.
     */
    public void setFax(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Fax</code>.
     */
    public String getFax() {
        return (String) get(8);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.OpenBank_Holidays</code>.
     */
    public void setOpenbankHolidays(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.OpenBank_Holidays</code>.
     */
    public Boolean getOpenbankHolidays() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Open_text</code>.
     */
    public void setOpenText(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Open_text</code>.
     */
    public String getOpenText() {
        return (String) get(10);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Location_Desc</code>.
     */
    public void setLocationDesc(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Location_Desc</code>.
     */
    public String getLocationDesc() {
        return (String) get(11);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Airport</code>.
     */
    public void setAirport(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Airport</code>.
     */
    public Boolean getAirport() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Status</code>.
     */
    public void setStatus(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.pickup_before</code>.
     */
    public void setPickupBefore(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.pickup_before</code>.
     */
    public Boolean getPickupBefore() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.pickup_after</code>.
     */
    public void setPickupAfter(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.pickup_after</code>.
     */
    public Boolean getPickupAfter() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.dropoff_before</code>.
     */
    public void setDropoffBefore(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.dropoff_before</code>.
     */
    public Boolean getDropoffBefore() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.dropoff_after</code>.
     */
    public void setDropoffAfter(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.dropoff_after</code>.
     */
    public Boolean getDropoffAfter() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.afterhrs_pickup_DELETE</code>.
     */
    public void setAfterhrsPickupDelete(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.afterhrs_pickup_DELETE</code>.
     */
    public Boolean getAfterhrsPickupDelete() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.afterhrs_dropoff_DELETE</code>.
     */
    public void setAfterhrsDropoffDelete(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.afterhrs_dropoff_DELETE</code>.
     */
    public Boolean getAfterhrsDropoffDelete() {
        return (Boolean) get(19);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Page_Title</code>.
     */
    public void setPageTitle(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Page_Title</code>.
     */
    public String getPageTitle() {
        return (String) get(20);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Meta_Description</code>.
     */
    public void setMetaDescription(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Meta_Description</code>.
     */
    public String getMetaDescription() {
        return (String) get(21);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Meta_Keywords</code>.
     */
    public void setMetaKeywords(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Meta_Keywords</code>.
     */
    public String getMetaKeywords() {
        return (String) get(22);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Location_Image</code>.
     */
    public void setLocationImage(byte... value) {
        set(23, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Location_Image</code>.
     */
    public byte[] getLocationImage() {
        return (byte[]) get(23);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Image_Width</code>.
     */
    public void setImageWidth(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Image_Width</code>.
     */
    public String getImageWidth() {
        return (String) get(24);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Image_Height</code>.
     */
    public void setImageHeight(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Image_Height</code>.
     */
    public String getImageHeight() {
        return (String) get(25);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.image_above</code>.
     */
    public void setImageAbove(Short value) {
        set(26, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.image_above</code>.
     */
    public Short getImageAbove() {
        return (Short) get(26);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Updated</code>.
     */
    public void setUpdated(Boolean value) {
        set(27, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Updated</code>.
     */
    public Boolean getUpdated() {
        return (Boolean) get(27);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Index_Display</code>.
     */
    public void setIndexDisplay(Boolean value) {
        set(28, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Index_Display</code>.
     */
    public Boolean getIndexDisplay() {
        return (Boolean) get(28);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Index_Name</code>.
     */
    public void setIndexName(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Index_Name</code>.
     */
    public String getIndexName() {
        return (String) get(29);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Alt_URL</code>.
     */
    public void setAltUrl(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Alt_URL</code>.
     */
    public String getAltUrl() {
        return (String) get(30);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.airport_code</code>.
     */
    public void setAirportCode(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.airport_code</code>.
     */
    public String getAirportCode() {
        return (String) get(31);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.contact_phone</code>.
     */
    public void setContactPhone(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.contact_phone</code>.
     */
    public String getContactPhone() {
        return (String) get(32);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.Car_Agent_ID</code>.
     */
    public void setCarAgentId(Integer value) {
        set(33, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.Car_Agent_ID</code>.
     */
    public Integer getCarAgentId() {
        return (Integer) get(33);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.allow_pickup_only</code>.
     */
    public void setAllowPickupOnly(Boolean value) {
        set(34, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.allow_pickup_only</code>.
     */
    public Boolean getAllowPickupOnly() {
        return (Boolean) get(34);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.allow_drop_only</code>.
     */
    public void setAllowDropOnly(Integer value) {
        set(35, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.allow_drop_only</code>.
     */
    public Integer getAllowDropOnly() {
        return (Integer) get(35);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.agent_loc_id</code>.
     */
    public void setAgentLocId(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.agent_loc_id</code>.
     */
    public String getAgentLocId() {
        return (String) get(36);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.NI_Location</code>.
     */
    public void setNiLocation(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.NI_Location</code>.
     */
    public Integer getNiLocation() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.location_name_de</code>.
     */
    public void setLocationNameDe(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.location_name_de</code>.
     */
    public String getLocationNameDe() {
        return (String) get(38);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.iata_city_code</code>.
     */
    public void setIataCityCode(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.iata_city_code</code>.
     */
    public String getIataCityCode() {
        return (String) get(39);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(40, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(40);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(41, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(41);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.cityname</code>.
     */
    public void setCityname(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.cityname</code>.
     */
    public String getCityname() {
        return (String) get(42);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.postalcode</code>.
     */
    public void setPostalcode(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.postalcode</code>.
     */
    public String getPostalcode() {
        return (String) get(43);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.county</code>.
     */
    public void setCounty(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.county</code>.
     */
    public String getCounty() {
        return (String) get(44);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.stateprov</code>.
     */
    public void setStateprov(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.stateprov</code>.
     */
    public String getStateprov() {
        return (String) get(45);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.addressline</code>.
     */
    public void setAddressline(String value) {
        set(46, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.addressline</code>.
     */
    public String getAddressline() {
        return (String) get(46);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.statecode</code>.
     */
    public void setStatecode(String value) {
        set(47, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.statecode</code>.
     */
    public String getStatecode() {
        return (String) get(47);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.bookingCountLast28</code>.
     */
    public void setBookingcountlast28(Integer value) {
        set(48, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.bookingCountLast28</code>.
     */
    public Integer getBookingcountlast28() {
        return (Integer) get(48);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.seoLocationName</code>.
     */
    public void setSeolocationname(String value) {
        set(49, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.seoLocationName</code>.
     */
    public String getSeolocationname() {
        return (String) get(49);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.directions_text</code>.
     */
    public void setDirectionsText(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.directions_text</code>.
     */
    public String getDirectionsText() {
        return (String) get(50);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.railway</code>.
     */
    public void setRailway(Boolean value) {
        set(51, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.railway</code>.
     */
    public Boolean getRailway() {
        return (Boolean) get(51);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.ferryport</code>.
     */
    public void setFerryport(Boolean value) {
        set(52, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.ferryport</code>.
     */
    public Boolean getFerryport() {
        return (Boolean) get(52);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.amendedBy</code>.
     */
    public void setAmendedby(Integer value) {
        set(53, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.amendedBy</code>.
     */
    public Integer getAmendedby() {
        return (Integer) get(53);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.fk_timezones</code>.
     */
    public void setFkTimezones(Integer value) {
        set(54, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.fk_timezones</code>.
     */
    public Integer getFkTimezones() {
        return (Integer) get(54);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.globalUniqueID</code>.
     */
    public void setGlobaluniqueid(Integer value) {
        set(55, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.globalUniqueID</code>.
     */
    public Integer getGlobaluniqueid() {
        return (Integer) get(55);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.Location.queriesThisYear</code>.
     */
    public void setQueriesthisyear(Integer value) {
        set(56, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.Location.queriesThisYear</code>.
     */
    public Integer getQueriesthisyear() {
        return (Integer) get(56);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationRecord
     */
    public LocationRecord() {
        super(Location.LOCATION);
    }

    /**
     * Create a detached, initialised LocationRecord
     */
    public LocationRecord(Integer locationId, Integer agencyId, String locationName, Long displayOrder, String locationAddress, String countryId, String locationEmail, String phone, String fax, Boolean openbankHolidays, String openText, String locationDesc, Boolean airport, Integer status, Boolean pickupBefore, Boolean pickupAfter, Boolean dropoffBefore, Boolean dropoffAfter, Boolean afterhrsPickupDelete, Boolean afterhrsDropoffDelete, String pageTitle, String metaDescription, String metaKeywords, byte[] locationImage, String imageWidth, String imageHeight, Short imageAbove, Boolean updated, Boolean indexDisplay, String indexName, String altUrl, String airportCode, String contactPhone, Integer carAgentId, Boolean allowPickupOnly, Integer allowDropOnly, String agentLocId, Integer niLocation, String locationNameDe, String iataCityCode, BigDecimal latitude, BigDecimal longitude, String cityname, String postalcode, String county, String stateprov, String addressline, String statecode, Integer bookingcountlast28, String seolocationname, String directionsText, Boolean railway, Boolean ferryport, Integer amendedby, Integer fkTimezones, Integer globaluniqueid, Integer queriesthisyear) {
        super(Location.LOCATION);

        set(0, locationId);
        set(1, agencyId);
        set(2, locationName);
        set(3, displayOrder);
        set(4, locationAddress);
        set(5, countryId);
        set(6, locationEmail);
        set(7, phone);
        set(8, fax);
        set(9, openbankHolidays);
        set(10, openText);
        set(11, locationDesc);
        set(12, airport);
        set(13, status);
        set(14, pickupBefore);
        set(15, pickupAfter);
        set(16, dropoffBefore);
        set(17, dropoffAfter);
        set(18, afterhrsPickupDelete);
        set(19, afterhrsDropoffDelete);
        set(20, pageTitle);
        set(21, metaDescription);
        set(22, metaKeywords);
        set(23, locationImage);
        set(24, imageWidth);
        set(25, imageHeight);
        set(26, imageAbove);
        set(27, updated);
        set(28, indexDisplay);
        set(29, indexName);
        set(30, altUrl);
        set(31, airportCode);
        set(32, contactPhone);
        set(33, carAgentId);
        set(34, allowPickupOnly);
        set(35, allowDropOnly);
        set(36, agentLocId);
        set(37, niLocation);
        set(38, locationNameDe);
        set(39, iataCityCode);
        set(40, latitude);
        set(41, longitude);
        set(42, cityname);
        set(43, postalcode);
        set(44, county);
        set(45, stateprov);
        set(46, addressline);
        set(47, statecode);
        set(48, bookingcountlast28);
        set(49, seolocationname);
        set(50, directionsText);
        set(51, railway);
        set(52, ferryport);
        set(53, amendedby);
        set(54, fkTimezones);
        set(55, globaluniqueid);
        set(56, queriesthisyear);
    }
}
