/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.MarketingLocationClientscope;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarketingLocationClientscopeRecord extends UpdatableRecordImpl<MarketingLocationClientscopeRecord> implements Record4<Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 306530539;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.marketing_location_clientscope.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.marketing_location_clientscope.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.marketing_location_clientscope.fk_client</code>.
     */
    public void setFkClient(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.marketing_location_clientscope.fk_client</code>.
     */
    public Integer getFkClient() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.marketing_location_clientscope.marketing_location_id</code>.
     */
    public void setMarketingLocationId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.marketing_location_clientscope.marketing_location_id</code>.
     */
    public Integer getMarketingLocationId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.marketing_location_clientscope.country_id</code>.
     */
    public void setCountryId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.marketing_location_clientscope.country_id</code>.
     */
    public String getCountryId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MarketingLocationClientscope.MARKETING_LOCATION_CLIENTSCOPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MarketingLocationClientscope.MARKETING_LOCATION_CLIENTSCOPE.FK_CLIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MarketingLocationClientscope.MARKETING_LOCATION_CLIENTSCOPE.MARKETING_LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MarketingLocationClientscope.MARKETING_LOCATION_CLIENTSCOPE.COUNTRY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFkClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMarketingLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCountryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFkClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMarketingLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCountryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingLocationClientscopeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingLocationClientscopeRecord value2(Integer value) {
        setFkClient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingLocationClientscopeRecord value3(Integer value) {
        setMarketingLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingLocationClientscopeRecord value4(String value) {
        setCountryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarketingLocationClientscopeRecord values(Integer value1, Integer value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarketingLocationClientscopeRecord
     */
    public MarketingLocationClientscopeRecord() {
        super(MarketingLocationClientscope.MARKETING_LOCATION_CLIENTSCOPE);
    }

    /**
     * Create a detached, initialised MarketingLocationClientscopeRecord
     */
    public MarketingLocationClientscopeRecord(Integer id, Integer fkClient, Integer marketingLocationId, String countryId) {
        super(MarketingLocationClientscope.MARKETING_LOCATION_CLIENTSCOPE);

        set(0, id);
        set(1, fkClient);
        set(2, marketingLocationId);
        set(3, countryId);
    }
}
