/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.Marketanalyserjobs;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarketanalyserjobsRecord extends UpdatableRecordImpl<MarketanalyserjobsRecord> {

    private static final long serialVersionUID = 750005031;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.guid</code>.
     */
    public void setGuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.guid</code>.
     */
    public UUID getGuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.id</code>.
     */
    public void setId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.id</code>.
     */
    public Integer getId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.fk_marketanalysis</code>.
     */
    public void setFkMarketanalysis(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.fk_marketanalysis</code>.
     */
    public Integer getFkMarketanalysis() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleAtHour</code>.
     */
    public void setScheduleathour(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleAtHour</code>.
     */
    public Integer getScheduleathour() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleEndHour</code>.
     */
    public void setScheduleendhour(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleEndHour</code>.
     */
    public Integer getScheduleendhour() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleWeekdaysOnly</code>.
     */
    public void setScheduleweekdaysonly(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleWeekdaysOnly</code>.
     */
    public Boolean getScheduleweekdaysonly() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleInterval</code>.
     */
    public void setScheduleinterval(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleInterval</code>.
     */
    public Integer getScheduleinterval() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleDayOfWeek</code>.
     */
    public void setScheduledayofweek(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleDayOfWeek</code>.
     */
    public Integer getScheduledayofweek() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleWhenMonthly</code>.
     */
    public void setSchedulewhenmonthly(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleWhenMonthly</code>.
     */
    public Integer getSchedulewhenmonthly() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.lastRunTime</code>.
     */
    public void setLastruntime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.lastRunTime</code>.
     */
    public Timestamp getLastruntime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.nextRunTimeInformationalOnly</code>.
     */
    public void setNextruntimeinformationalonly(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.nextRunTimeInformationalOnly</code>.
     */
    public Timestamp getNextruntimeinformationalonly() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.fk_user</code>.
     */
    public void setFkUser(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.fk_user</code>.
     */
    public Integer getFkUser() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.pickupDate</code>.
     */
    public void setPickupdate(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.pickupDate</code>.
     */
    public Timestamp getPickupdate() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dropoffDate</code>.
     */
    public void setDropoffdate(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dropoffDate</code>.
     */
    public Timestamp getDropoffdate() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.absoluteReduction</code>.
     */
    public void setAbsolutereduction(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.absoluteReduction</code>.
     */
    public BigDecimal getAbsolutereduction() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.percentageReduction</code>.
     */
    public void setPercentagereduction(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.percentageReduction</code>.
     */
    public BigDecimal getPercentagereduction() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.channel</code>.
     */
    public void setChannel(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.channel</code>.
     */
    public Integer getChannel() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.effectiveFrom</code>.
     */
    public void setEffectivefrom(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.effectiveFrom</code>.
     */
    public Timestamp getEffectivefrom() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.effectiveTo</code>.
     */
    public void setEffectiveto(Timestamp value) {
        set(19, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.effectiveTo</code>.
     */
    public Timestamp getEffectiveto() {
        return (Timestamp) get(19);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.minRank</code>.
     */
    public void setMinrank(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.minRank</code>.
     */
    public Integer getMinrank() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.minThreshold</code>.
     */
    public void setMinthreshold(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.minThreshold</code>.
     */
    public Integer getMinthreshold() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.maxThreshold</code>.
     */
    public void setMaxthreshold(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.maxThreshold</code>.
     */
    public Integer getMaxthreshold() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.products</code>.
     */
    public void setProducts(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.products</code>.
     */
    public String getProducts() {
        return (String) get(23);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.status</code>.
     */
    public void setStatus(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.status</code>.
     */
    public String getStatus() {
        return (String) get(24);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.lastUpdated</code>.
     */
    public void setLastupdated(Timestamp value) {
        set(25, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.lastUpdated</code>.
     */
    public Timestamp getLastupdated() {
        return (Timestamp) get(25);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.runImmediatelyUserID</code>.
     */
    public void setRunimmediatelyuserid(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.runImmediatelyUserID</code>.
     */
    public Integer getRunimmediatelyuserid() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.stopImmediatelyUserID</code>.
     */
    public void setStopimmediatelyuserid(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.stopImmediatelyUserID</code>.
     */
    public Integer getStopimmediatelyuserid() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.errorCount</code>.
     */
    public void setErrorcount(Integer value) {
        set(28, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.errorCount</code>.
     */
    public Integer getErrorcount() {
        return (Integer) get(28);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.lastRunFor</code>.
     */
    public void setLastrunfor(Integer value) {
        set(29, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.lastRunFor</code>.
     */
    public Integer getLastrunfor() {
        return (Integer) get(29);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.runningSince</code>.
     */
    public void setRunningsince(Timestamp value) {
        set(30, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.runningSince</code>.
     */
    public Timestamp getRunningsince() {
        return (Timestamp) get(30);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.message</code>.
     */
    public void setMessage(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.message</code>.
     */
    public String getMessage() {
        return (String) get(31);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.priority</code>.
     */
    public void setPriority(Integer value) {
        set(32, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(32);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.ignoreCacheForNonReference</code>.
     */
    public void setIgnorecachefornonreference(Boolean value) {
        set(33, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.ignoreCacheForNonReference</code>.
     */
    public Boolean getIgnorecachefornonreference() {
        return (Boolean) get(33);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.effectiveDays</code>.
     */
    public void setEffectivedays(Integer value) {
        set(34, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.effectiveDays</code>.
     */
    public Integer getEffectivedays() {
        return (Integer) get(34);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.hourFrequency</code>.
     */
    public void setHourfrequency(Integer value) {
        set(35, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.hourFrequency</code>.
     */
    public Integer getHourfrequency() {
        return (Integer) get(35);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.weekFrequency</code>.
     */
    public void setWeekfrequency(Integer value) {
        set(36, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.weekFrequency</code>.
     */
    public Integer getWeekfrequency() {
        return (Integer) get(36);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dayFrequency</code>.
     */
    public void setDayfrequency(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dayFrequency</code>.
     */
    public Integer getDayfrequency() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleDayOfWeek2</code>.
     */
    public void setScheduledayofweek2(Integer value) {
        set(38, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleDayOfWeek2</code>.
     */
    public Integer getScheduledayofweek2() {
        return (Integer) get(38);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.topRank</code>.
     */
    public void setToprank(Integer value) {
        set(39, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.topRank</code>.
     */
    public Integer getToprank() {
        return (Integer) get(39);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dynamicMargins</code>.
     */
    public void setDynamicmargins(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dynamicMargins</code>.
     */
    public String getDynamicmargins() {
        return (String) get(40);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.useDynamicMargins</code>.
     */
    public void setUsedynamicmargins(Boolean value) {
        set(41, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.useDynamicMargins</code>.
     */
    public Boolean getUsedynamicmargins() {
        return (Boolean) get(41);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.ignoreCompetitors</code>.
     */
    public void setIgnorecompetitors(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.ignoreCompetitors</code>.
     */
    public String getIgnorecompetitors() {
        return (String) get(42);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dow_start</code>.
     */
    public void setDowStart(Short value) {
        set(43, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dow_start</code>.
     */
    public Short getDowStart() {
        return (Short) get(43);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.start_time</code>.
     */
    public void setStartTime(Short value) {
        set(44, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.start_time</code>.
     */
    public Short getStartTime() {
        return (Short) get(44);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dow_end</code>.
     */
    public void setDowEnd(Short value) {
        set(45, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.dow_end</code>.
     */
    public Short getDowEnd() {
        return (Short) get(45);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.end_time</code>.
     */
    public void setEndTime(Short value) {
        set(46, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.end_time</code>.
     */
    public Short getEndTime() {
        return (Short) get(46);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.execTimeSecs</code>.
     */
    public void setExectimesecs(Short value) {
        set(47, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.execTimeSecs</code>.
     */
    public Short getExectimesecs() {
        return (Short) get(47);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleMinute</code>.
     */
    public void setScheduleminute(UByte value) {
        set(48, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scheduleMinute</code>.
     */
    public UByte getScheduleminute() {
        return (UByte) get(48);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.fk_safetynet</code>.
     */
    public void setFkSafetynet(Integer value) {
        set(49, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.fk_safetynet</code>.
     */
    public Integer getFkSafetynet() {
        return (Integer) get(49);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.is_disabled</code>.
     */
    public void setIsDisabled(Boolean value) {
        set(50, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.is_disabled</code>.
     */
    public Boolean getIsDisabled() {
        return (Boolean) get(50);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.is_rentalcars</code>.
     */
    public void setIsRentalcars(Boolean value) {
        set(51, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.is_rentalcars</code>.
     */
    public Boolean getIsRentalcars() {
        return (Boolean) get(51);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.is_automated</code>.
     */
    public void setIsAutomated(Boolean value) {
        set(52, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.is_automated</code>.
     */
    public Boolean getIsAutomated() {
        return (Boolean) get(52);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.advance_time</code>.
     */
    public void setAdvanceTime(Integer value) {
        set(53, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.advance_time</code>.
     */
    public Integer getAdvanceTime() {
        return (Integer) get(53);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.duration</code>.
     */
    public void setDuration(Integer value) {
        set(54, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(54);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scrape_pickup_date</code>.
     */
    public void setScrapePickupDate(Timestamp value) {
        set(55, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.MarketAnalyserJobs.scrape_pickup_date</code>.
     */
    public Timestamp getScrapePickupDate() {
        return (Timestamp) get(55);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarketanalyserjobsRecord
     */
    public MarketanalyserjobsRecord() {
        super(Marketanalyserjobs.MARKETANALYSERJOBS);
    }

    /**
     * Create a detached, initialised MarketanalyserjobsRecord
     */
    public MarketanalyserjobsRecord(UUID guid, Integer id, Integer fkMarketanalysis, String description, Integer scheduleathour, Integer scheduleendhour, Boolean scheduleweekdaysonly, Integer scheduleinterval, Integer scheduledayofweek, Integer schedulewhenmonthly, Timestamp lastruntime, Timestamp nextruntimeinformationalonly, Integer fkUser, Timestamp pickupdate, Timestamp dropoffdate, BigDecimal absolutereduction, BigDecimal percentagereduction, Integer channel, Timestamp effectivefrom, Timestamp effectiveto, Integer minrank, Integer minthreshold, Integer maxthreshold, String products, String status, Timestamp lastupdated, Integer runimmediatelyuserid, Integer stopimmediatelyuserid, Integer errorcount, Integer lastrunfor, Timestamp runningsince, String message, Integer priority, Boolean ignorecachefornonreference, Integer effectivedays, Integer hourfrequency, Integer weekfrequency, Integer dayfrequency, Integer scheduledayofweek2, Integer toprank, String dynamicmargins, Boolean usedynamicmargins, String ignorecompetitors, Short dowStart, Short startTime, Short dowEnd, Short endTime, Short exectimesecs, UByte scheduleminute, Integer fkSafetynet, Boolean isDisabled, Boolean isRentalcars, Boolean isAutomated, Integer advanceTime, Integer duration, Timestamp scrapePickupDate) {
        super(Marketanalyserjobs.MARKETANALYSERJOBS);

        set(0, guid);
        set(1, id);
        set(2, fkMarketanalysis);
        set(3, description);
        set(4, scheduleathour);
        set(5, scheduleendhour);
        set(6, scheduleweekdaysonly);
        set(7, scheduleinterval);
        set(8, scheduledayofweek);
        set(9, schedulewhenmonthly);
        set(10, lastruntime);
        set(11, nextruntimeinformationalonly);
        set(12, fkUser);
        set(13, pickupdate);
        set(14, dropoffdate);
        set(15, absolutereduction);
        set(16, percentagereduction);
        set(17, channel);
        set(18, effectivefrom);
        set(19, effectiveto);
        set(20, minrank);
        set(21, minthreshold);
        set(22, maxthreshold);
        set(23, products);
        set(24, status);
        set(25, lastupdated);
        set(26, runimmediatelyuserid);
        set(27, stopimmediatelyuserid);
        set(28, errorcount);
        set(29, lastrunfor);
        set(30, runningsince);
        set(31, message);
        set(32, priority);
        set(33, ignorecachefornonreference);
        set(34, effectivedays);
        set(35, hourfrequency);
        set(36, weekfrequency);
        set(37, dayfrequency);
        set(38, scheduledayofweek2);
        set(39, toprank);
        set(40, dynamicmargins);
        set(41, usedynamicmargins);
        set(42, ignorecompetitors);
        set(43, dowStart);
        set(44, startTime);
        set(45, dowEnd);
        set(46, endTime);
        set(47, exectimesecs);
        set(48, scheduleminute);
        set(49, fkSafetynet);
        set(50, isDisabled);
        set(51, isRentalcars);
        set(52, isAutomated);
        set(53, advanceTime);
        set(54, duration);
        set(55, scrapePickupDate);
    }
}
