/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.OptimizationElasticityAdjustments;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptimizationElasticityAdjustmentsRecord extends UpdatableRecordImpl<OptimizationElasticityAdjustmentsRecord> implements Record21<Integer, Integer, String, Integer, BigDecimal, Integer, BigDecimal, String, String, Integer, Integer, Integer, Integer, Integer, String, Timestamp, Integer, Integer, Boolean, Integer, Boolean> {

    private static final long serialVersionUID = 621584341;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.channel_group</code>.
     */
    public void setChannelGroup(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.channel_group</code>.
     */
    public Integer getChannelGroup() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.channel_corridor</code>.
     */
    public void setChannelCorridor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.channel_corridor</code>.
     */
    public String getChannelCorridor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.fk_channel</code>.
     */
    public void setFkChannel(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.fk_channel</code>.
     */
    public Integer getFkChannel() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.adjustment_final</code>.
     */
    public void setAdjustmentFinal(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.adjustment_final</code>.
     */
    public BigDecimal getAdjustmentFinal() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.fk_client</code>.
     */
    public void setFkClient(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.fk_client</code>.
     */
    public Integer getFkClient() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.adjustment_final_test</code>.
     */
    public void setAdjustmentFinalTest(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.adjustment_final_test</code>.
     */
    public BigDecimal getAdjustmentFinalTest() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.origin_country</code>.
     */
    public void setOriginCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.origin_country</code>.
     */
    public String getOriginCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.destination_country</code>.
     */
    public void setDestinationCountry(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.destination_country</code>.
     */
    public String getDestinationCountry() {
        return (String) get(8);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.transition_flag</code>.
     */
    public void setTransitionFlag(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.transition_flag</code>.
     */
    public Integer getTransitionFlag() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.min_rental_duration</code>.
     */
    public void setMinRentalDuration(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.min_rental_duration</code>.
     */
    public Integer getMinRentalDuration() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.max_rental_duration</code>.
     */
    public void setMaxRentalDuration(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.max_rental_duration</code>.
     */
    public Integer getMaxRentalDuration() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.min_pickup_lead</code>.
     */
    public void setMinPickupLead(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.min_pickup_lead</code>.
     */
    public Integer getMinPickupLead() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.max_pickup_lead</code>.
     */
    public void setMaxPickupLead(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.max_pickup_lead</code>.
     */
    public Integer getMaxPickupLead() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.car_group</code>.
     */
    public void setCarGroup(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.car_group</code>.
     */
    public String getCarGroup() {
        return (String) get(14);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.amend_date</code>.
     */
    public void setAmendDate(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.amend_date</code>.
     */
    public Timestamp getAmendDate() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.amended_by</code>.
     */
    public void setAmendedBy(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.amended_by</code>.
     */
    public Integer getAmendedBy() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.location_id</code>.
     */
    public void setLocationId(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.location_id</code>.
     */
    public Integer getLocationId() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.ab_testing</code>.
     */
    public void setAbTesting(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.ab_testing</code>.
     */
    public Boolean getAbTesting() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.version</code>.
     */
    public void setVersion(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.hill_climbing</code>.
     */
    public void setHillClimbing(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.optimization_elasticity_adjustments.hill_climbing</code>.
     */
    public Boolean getHillClimbing() {
        return (Boolean) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Integer, Integer, String, Integer, BigDecimal, Integer, BigDecimal, String, String, Integer, Integer, Integer, Integer, Integer, String, Timestamp, Integer, Integer, Boolean, Integer, Boolean> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Integer, Integer, String, Integer, BigDecimal, Integer, BigDecimal, String, String, Integer, Integer, Integer, Integer, Integer, String, Timestamp, Integer, Integer, Boolean, Integer, Boolean> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.CHANNEL_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.CHANNEL_CORRIDOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.FK_CHANNEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.ADJUSTMENT_FINAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.FK_CLIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.ADJUSTMENT_FINAL_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.ORIGIN_COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.DESTINATION_COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.TRANSITION_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.MIN_RENTAL_DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.MAX_RENTAL_DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.MIN_PICKUP_LEAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.MAX_PICKUP_LEAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.CAR_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.AMEND_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.AMENDED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.LOCATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field19() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.AB_TESTING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field20() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field21() {
        return OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS.HILL_CLIMBING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getChannelGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getChannelCorridor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getFkChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getAdjustmentFinal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getFkClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getAdjustmentFinalTest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getOriginCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDestinationCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getTransitionFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getMinRentalDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getMaxRentalDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getMinPickupLead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getMaxPickupLead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getCarGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getAmendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component17() {
        return getAmendedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component18() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component19() {
        return getAbTesting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component20() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component21() {
        return getHillClimbing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getChannelGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getChannelCorridor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getFkChannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getAdjustmentFinal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFkClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getAdjustmentFinalTest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getOriginCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDestinationCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getTransitionFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getMinRentalDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getMaxRentalDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getMinPickupLead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getMaxPickupLead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getCarGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getAmendDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getAmendedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getLocationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value19() {
        return getAbTesting();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value20() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value21() {
        return getHillClimbing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value2(Integer value) {
        setChannelGroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value3(String value) {
        setChannelCorridor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value4(Integer value) {
        setFkChannel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value5(BigDecimal value) {
        setAdjustmentFinal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value6(Integer value) {
        setFkClient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value7(BigDecimal value) {
        setAdjustmentFinalTest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value8(String value) {
        setOriginCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value9(String value) {
        setDestinationCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value10(Integer value) {
        setTransitionFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value11(Integer value) {
        setMinRentalDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value12(Integer value) {
        setMaxRentalDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value13(Integer value) {
        setMinPickupLead(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value14(Integer value) {
        setMaxPickupLead(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value15(String value) {
        setCarGroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value16(Timestamp value) {
        setAmendDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value17(Integer value) {
        setAmendedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value18(Integer value) {
        setLocationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value19(Boolean value) {
        setAbTesting(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value20(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord value21(Boolean value) {
        setHillClimbing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OptimizationElasticityAdjustmentsRecord values(Integer value1, Integer value2, String value3, Integer value4, BigDecimal value5, Integer value6, BigDecimal value7, String value8, String value9, Integer value10, Integer value11, Integer value12, Integer value13, Integer value14, String value15, Timestamp value16, Integer value17, Integer value18, Boolean value19, Integer value20, Boolean value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OptimizationElasticityAdjustmentsRecord
     */
    public OptimizationElasticityAdjustmentsRecord() {
        super(OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS);
    }

    /**
     * Create a detached, initialised OptimizationElasticityAdjustmentsRecord
     */
    public OptimizationElasticityAdjustmentsRecord(Integer id, Integer channelGroup, String channelCorridor, Integer fkChannel, BigDecimal adjustmentFinal, Integer fkClient, BigDecimal adjustmentFinalTest, String originCountry, String destinationCountry, Integer transitionFlag, Integer minRentalDuration, Integer maxRentalDuration, Integer minPickupLead, Integer maxPickupLead, String carGroup, Timestamp amendDate, Integer amendedBy, Integer locationId, Boolean abTesting, Integer version, Boolean hillClimbing) {
        super(OptimizationElasticityAdjustments.OPTIMIZATION_ELASTICITY_ADJUSTMENTS);

        set(0, id);
        set(1, channelGroup);
        set(2, channelCorridor);
        set(3, fkChannel);
        set(4, adjustmentFinal);
        set(5, fkClient);
        set(6, adjustmentFinalTest);
        set(7, originCountry);
        set(8, destinationCountry);
        set(9, transitionFlag);
        set(10, minRentalDuration);
        set(11, maxRentalDuration);
        set(12, minPickupLead);
        set(13, maxPickupLead);
        set(14, carGroup);
        set(15, amendDate);
        set(16, amendedBy);
        set(17, locationId);
        set(18, abTesting);
        set(19, version);
        set(20, hillClimbing);
    }
}
