/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.PricingRuleTable;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PricingRuleTableRecord extends UpdatableRecordImpl<PricingRuleTableRecord> implements Record18<Integer, Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, Integer, BigDecimal, BigDecimal, BigDecimal, Timestamp> {

    private static final long serialVersionUID = 396458197;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.control_id</code>.
     */
    public void setControlId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.control_id</code>.
     */
    public Integer getControlId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.test_id</code>.
     */
    public void setTestId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.test_id</code>.
     */
    public Integer getTestId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.test_bucket</code>.
     */
    public void setTestBucket(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.test_bucket</code>.
     */
    public String getTestBucket() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.corridor_id</code>.
     */
    public void setCorridorId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.corridor_id</code>.
     */
    public Integer getCorridorId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.duration_min</code>.
     */
    public void setDurationMin(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.duration_min</code>.
     */
    public Integer getDurationMin() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.duration_max</code>.
     */
    public void setDurationMax(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.duration_max</code>.
     */
    public Integer getDurationMax() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.lead_min</code>.
     */
    public void setLeadMin(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.lead_min</code>.
     */
    public Integer getLeadMin() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.lead_max</code>.
     */
    public void setLeadMax(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.lead_max</code>.
     */
    public Integer getLeadMax() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.pax_min</code>.
     */
    public void setPaxMin(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.pax_min</code>.
     */
    public Integer getPaxMin() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.pax_max</code>.
     */
    public void setPaxMax(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.pax_max</code>.
     */
    public Integer getPaxMax() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.flightfare_min</code>.
     */
    public void setFlightfareMin(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.flightfare_min</code>.
     */
    public BigDecimal getFlightfareMin() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.flightfare_max</code>.
     */
    public void setFlightfareMax(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.flightfare_max</code>.
     */
    public BigDecimal getFlightfareMax() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.pricing_type</code>.
     */
    public void setPricingType(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.pricing_type</code>.
     */
    public Integer getPricingType() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.pricing_value</code>.
     */
    public void setPricingValue(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.pricing_value</code>.
     */
    public BigDecimal getPricingValue() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.min_boundary</code>.
     */
    public void setMinBoundary(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.min_boundary</code>.
     */
    public BigDecimal getMinBoundary() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.max_boundary</code>.
     */
    public void setMaxBoundary(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.max_boundary</code>.
     */
    public BigDecimal getMaxBoundary() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.udatetime</code>.
     */
    public void setUdatetime(Timestamp value) {
        set(17, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.pricing_rule_table.udatetime</code>.
     */
    public Timestamp getUdatetime() {
        return (Timestamp) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, Integer, BigDecimal, BigDecimal, BigDecimal, Timestamp> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal, Integer, BigDecimal, BigDecimal, BigDecimal, Timestamp> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PricingRuleTable.PRICING_RULE_TABLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PricingRuleTable.PRICING_RULE_TABLE.CONTROL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PricingRuleTable.PRICING_RULE_TABLE.TEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PricingRuleTable.PRICING_RULE_TABLE.TEST_BUCKET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return PricingRuleTable.PRICING_RULE_TABLE.CORRIDOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return PricingRuleTable.PRICING_RULE_TABLE.DURATION_MIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return PricingRuleTable.PRICING_RULE_TABLE.DURATION_MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return PricingRuleTable.PRICING_RULE_TABLE.LEAD_MIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return PricingRuleTable.PRICING_RULE_TABLE.LEAD_MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return PricingRuleTable.PRICING_RULE_TABLE.PAX_MIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return PricingRuleTable.PRICING_RULE_TABLE.PAX_MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return PricingRuleTable.PRICING_RULE_TABLE.FLIGHTFARE_MIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field13() {
        return PricingRuleTable.PRICING_RULE_TABLE.FLIGHTFARE_MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return PricingRuleTable.PRICING_RULE_TABLE.PRICING_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return PricingRuleTable.PRICING_RULE_TABLE.PRICING_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field16() {
        return PricingRuleTable.PRICING_RULE_TABLE.MIN_BOUNDARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field17() {
        return PricingRuleTable.PRICING_RULE_TABLE.MAX_BOUNDARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return PricingRuleTable.PRICING_RULE_TABLE.UDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getControlId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTestBucket();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getCorridorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getDurationMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getDurationMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getLeadMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getLeadMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getPaxMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getPaxMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getFlightfareMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component13() {
        return getFlightfareMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getPricingType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component15() {
        return getPricingValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component16() {
        return getMinBoundary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component17() {
        return getMaxBoundary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getUdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getControlId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTestBucket();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCorridorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDurationMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDurationMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getLeadMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getLeadMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPaxMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getPaxMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getFlightfareMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value13() {
        return getFlightfareMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getPricingType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getPricingValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value16() {
        return getMinBoundary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value17() {
        return getMaxBoundary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getUdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value2(Integer value) {
        setControlId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value3(Integer value) {
        setTestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value4(String value) {
        setTestBucket(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value5(Integer value) {
        setCorridorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value6(Integer value) {
        setDurationMin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value7(Integer value) {
        setDurationMax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value8(Integer value) {
        setLeadMin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value9(Integer value) {
        setLeadMax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value10(Integer value) {
        setPaxMin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value11(Integer value) {
        setPaxMax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value12(BigDecimal value) {
        setFlightfareMin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value13(BigDecimal value) {
        setFlightfareMax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value14(Integer value) {
        setPricingType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value15(BigDecimal value) {
        setPricingValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value16(BigDecimal value) {
        setMinBoundary(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value17(BigDecimal value) {
        setMaxBoundary(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord value18(Timestamp value) {
        setUdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PricingRuleTableRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11, BigDecimal value12, BigDecimal value13, Integer value14, BigDecimal value15, BigDecimal value16, BigDecimal value17, Timestamp value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PricingRuleTableRecord
     */
    public PricingRuleTableRecord() {
        super(PricingRuleTable.PRICING_RULE_TABLE);
    }

    /**
     * Create a detached, initialised PricingRuleTableRecord
     */
    public PricingRuleTableRecord(Integer id, Integer controlId, Integer testId, String testBucket, Integer corridorId, Integer durationMin, Integer durationMax, Integer leadMin, Integer leadMax, Integer paxMin, Integer paxMax, BigDecimal flightfareMin, BigDecimal flightfareMax, Integer pricingType, BigDecimal pricingValue, BigDecimal minBoundary, BigDecimal maxBoundary, Timestamp udatetime) {
        super(PricingRuleTable.PRICING_RULE_TABLE);

        set(0, id);
        set(1, controlId);
        set(2, testId);
        set(3, testBucket);
        set(4, corridorId);
        set(5, durationMin);
        set(6, durationMax);
        set(7, leadMin);
        set(8, leadMax);
        set(9, paxMin);
        set(10, paxMax);
        set(11, flightfareMin);
        set(12, flightfareMax);
        set(13, pricingType);
        set(14, pricingValue);
        set(15, minBoundary);
        set(16, maxBoundary);
        set(17, udatetime);
    }
}
