/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.ReservationProblemInfo;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReservationProblemInfoRecord extends UpdatableRecordImpl<ReservationProblemInfoRecord> implements Record7<Integer, Integer, Integer, Timestamp, Integer, Timestamp, Integer> {

    private static final long serialVersionUID = -860246527;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.fk_reservation</code>.
     */
    public void setFkReservation(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.fk_reservation</code>.
     */
    public Integer getFkReservation() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.fk_error</code>.
     */
    public void setFkError(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.fk_error</code>.
     */
    public Integer getFkError() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.status</code>.
     */
    public void setStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.resolved_date</code>.
     */
    public void setResolvedDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.resolved_date</code>.
     */
    public Timestamp getResolvedDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.resolved_by</code>.
     */
    public void setResolvedBy(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.reservation_problem_info.resolved_by</code>.
     */
    public Integer getResolvedBy() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Timestamp, Integer, Timestamp, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Timestamp, Integer, Timestamp, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ReservationProblemInfo.RESERVATION_PROBLEM_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ReservationProblemInfo.RESERVATION_PROBLEM_INFO.FK_RESERVATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ReservationProblemInfo.RESERVATION_PROBLEM_INFO.FK_ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ReservationProblemInfo.RESERVATION_PROBLEM_INFO.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ReservationProblemInfo.RESERVATION_PROBLEM_INFO.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ReservationProblemInfo.RESERVATION_PROBLEM_INFO.RESOLVED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ReservationProblemInfo.RESERVATION_PROBLEM_INFO.RESOLVED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFkReservation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getFkError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getResolvedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getResolvedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFkReservation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFkError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getResolvedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getResolvedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationProblemInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationProblemInfoRecord value2(Integer value) {
        setFkReservation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationProblemInfoRecord value3(Integer value) {
        setFkError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationProblemInfoRecord value4(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationProblemInfoRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationProblemInfoRecord value6(Timestamp value) {
        setResolvedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationProblemInfoRecord value7(Integer value) {
        setResolvedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationProblemInfoRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Integer value5, Timestamp value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationProblemInfoRecord
     */
    public ReservationProblemInfoRecord() {
        super(ReservationProblemInfo.RESERVATION_PROBLEM_INFO);
    }

    /**
     * Create a detached, initialised ReservationProblemInfoRecord
     */
    public ReservationProblemInfoRecord(Integer id, Integer fkReservation, Integer fkError, Timestamp timestamp, Integer status, Timestamp resolvedDate, Integer resolvedBy) {
        super(ReservationProblemInfo.RESERVATION_PROBLEM_INFO);

        set(0, id);
        set(1, fkReservation);
        set(2, fkError);
        set(3, timestamp);
        set(4, status);
        set(5, resolvedDate);
        set(6, resolvedBy);
    }
}
