/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import java.util.UUID;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.RuleLocationGroupBak20170913;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RuleLocationGroupBak20170913Record extends TableRecordImpl<RuleLocationGroupBak20170913Record> implements Record5<UUID, Integer, Integer, String, String> {

    private static final long serialVersionUID = -818844109;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.guid</code>.
     */
    public void setGuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.guid</code>.
     */
    public UUID getGuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.rule_location_group_id</code>.
     */
    public void setRuleLocationGroupId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.rule_location_group_id</code>.
     */
    public Integer getRuleLocationGroupId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.car_agent_id</code>.
     */
    public void setCarAgentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.car_agent_id</code>.
     */
    public Integer getCarAgentId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.ids</code>.
     */
    public void setIds(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.rule_location_group_bak20170913.ids</code>.
     */
    public String getIds() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, Integer, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, Integer, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return RuleLocationGroupBak20170913.RULE_LOCATION_GROUP_BAK20170913.GUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RuleLocationGroupBak20170913.RULE_LOCATION_GROUP_BAK20170913.RULE_LOCATION_GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RuleLocationGroupBak20170913.RULE_LOCATION_GROUP_BAK20170913.CAR_AGENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RuleLocationGroupBak20170913.RULE_LOCATION_GROUP_BAK20170913.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RuleLocationGroupBak20170913.RULE_LOCATION_GROUP_BAK20170913.IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRuleLocationGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCarAgentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getGuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRuleLocationGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCarAgentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleLocationGroupBak20170913Record value1(UUID value) {
        setGuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleLocationGroupBak20170913Record value2(Integer value) {
        setRuleLocationGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleLocationGroupBak20170913Record value3(Integer value) {
        setCarAgentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleLocationGroupBak20170913Record value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleLocationGroupBak20170913Record value5(String value) {
        setIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RuleLocationGroupBak20170913Record values(UUID value1, Integer value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RuleLocationGroupBak20170913Record
     */
    public RuleLocationGroupBak20170913Record() {
        super(RuleLocationGroupBak20170913.RULE_LOCATION_GROUP_BAK20170913);
    }

    /**
     * Create a detached, initialised RuleLocationGroupBak20170913Record
     */
    public RuleLocationGroupBak20170913Record(UUID guid, Integer ruleLocationGroupId, Integer carAgentId, String name, String ids) {
        super(RuleLocationGroupBak20170913.RULE_LOCATION_GROUP_BAK20170913);

        set(0, guid);
        set(1, ruleLocationGroupId);
        set(2, carAgentId);
        set(3, name);
        set(4, ids);
    }
}
