/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.Syncobj_0x4531453235323638;

import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Syncobj_0x4531453235323638Record extends TableRecordImpl<Syncobj_0x4531453235323638Record> {

    private static final long serialVersionUID = -1496552746;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.amendedBy</code>.
     */
    public void setAmendedby(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.amendedBy</code>.
     */
    public Integer getAmendedby() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.amendDate</code>.
     */
    public void setAmenddate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.amendDate</code>.
     */
    public Timestamp getAmenddate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.consumerLocation</code>.
     */
    public void setConsumerlocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.consumerLocation</code>.
     */
    public String getConsumerlocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fromDate</code>.
     */
    public void setFromdate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fromDate</code>.
     */
    public Timestamp getFromdate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.toDate</code>.
     */
    public void setTodate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.toDate</code>.
     */
    public Timestamp getTodate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.onDashboard</code>.
     */
    public void setOndashboard(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.onDashboard</code>.
     */
    public Boolean getOndashboard() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.hoursBeforePickupTime</code>.
     */
    public void setHoursbeforepickuptime(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.hoursBeforePickupTime</code>.
     */
    public Integer getHoursbeforepickuptime() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.stopSale</code>.
     */
    public void setStopsale(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.stopSale</code>.
     */
    public Integer getStopsale() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_clientPlan</code>.
     */
    public void setFkClientplan(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_clientPlan</code>.
     */
    public Integer getFkClientplan() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.type</code>.
     */
    public void setType(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.type</code>.
     */
    public String getType() {
        return (String) get(11);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.blend</code>.
     */
    public void setBlend(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.blend</code>.
     */
    public Integer getBlend() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_user</code>.
     */
    public void setFkUser(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_user</code>.
     */
    public Integer getFkUser() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_org</code>.
     */
    public void setFkOrg(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_org</code>.
     */
    public Integer getFkOrg() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.exclusion</code>.
     */
    public void setExclusion(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.exclusion</code>.
     */
    public Boolean getExclusion() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_plan</code>.
     */
    public void setFkPlan(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_plan</code>.
     */
    public Integer getFkPlan() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_virtualPartnerChannel</code>.
     */
    public void setFkVirtualpartnerchannel(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_virtualPartnerChannel</code>.
     */
    public Integer getFkVirtualpartnerchannel() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.minimumAdvanceHours</code>.
     */
    public void setMinimumadvancehours(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.minimumAdvanceHours</code>.
     */
    public Integer getMinimumadvancehours() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.priority</code>.
     */
    public void setPriority(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.writeProtectedByUser</code>.
     */
    public void setWriteprotectedbyuser(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.writeProtectedByUser</code>.
     */
    public Integer getWriteprotectedbyuser() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_plan_downtown</code>.
     */
    public void setFkPlanDowntown(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_plan_downtown</code>.
     */
    public Integer getFkPlanDowntown() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.dashboardChannelType</code>.
     */
    public void setDashboardchanneltype(UByte value) {
        set(22, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.dashboardChannelType</code>.
     */
    public UByte getDashboardchanneltype() {
        return (UByte) get(22);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.cFlags</code>.
     */
    public void setCflags(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.cFlags</code>.
     */
    public Integer getCflags() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.dow_start</code>.
     */
    public void setDowStart(Short value) {
        set(24, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.dow_start</code>.
     */
    public Short getDowStart() {
        return (Short) get(24);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.start_time</code>.
     */
    public void setStartTime(Short value) {
        set(25, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.start_time</code>.
     */
    public Short getStartTime() {
        return (Short) get(25);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.dow_end</code>.
     */
    public void setDowEnd(Short value) {
        set(26, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.dow_end</code>.
     */
    public Short getDowEnd() {
        return (Short) get(26);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.end_time</code>.
     */
    public void setEndTime(Short value) {
        set(27, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.end_time</code>.
     */
    public Short getEndTime() {
        return (Short) get(27);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.schedule_type</code>.
     */
    public void setScheduleType(Short value) {
        set(28, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.schedule_type</code>.
     */
    public Short getScheduleType() {
        return (Short) get(28);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.keyValuePair</code>.
     */
    public void setKeyvaluepair(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.keyValuePair</code>.
     */
    public String getKeyvaluepair() {
        return (String) get(29);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_client_finance_group</code>.
     */
    public void setFkClientFinanceGroup(Integer value) {
        set(30, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.syncobj_0x4531453235323638.fk_client_finance_group</code>.
     */
    public Integer getFkClientFinanceGroup() {
        return (Integer) get(30);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Syncobj_0x4531453235323638Record
     */
    public Syncobj_0x4531453235323638Record() {
        super(Syncobj_0x4531453235323638.SYNCOBJ_0X4531453235323638);
    }

    /**
     * Create a detached, initialised Syncobj_0x4531453235323638Record
     */
    public Syncobj_0x4531453235323638Record(Integer id, String name, Integer amendedby, Timestamp amenddate, String consumerlocation, Timestamp fromdate, Timestamp todate, Boolean ondashboard, Integer hoursbeforepickuptime, Integer stopsale, Integer fkClientplan, String type, Integer blend, Integer fkUser, Integer fkOrg, Boolean exclusion, Integer fkPlan, Integer fkVirtualpartnerchannel, Integer minimumadvancehours, Integer priority, Integer writeprotectedbyuser, Integer fkPlanDowntown, UByte dashboardchanneltype, Integer cflags, Short dowStart, Short startTime, Short dowEnd, Short endTime, Short scheduleType, String keyvaluepair, Integer fkClientFinanceGroup) {
        super(Syncobj_0x4531453235323638.SYNCOBJ_0X4531453235323638);

        set(0, id);
        set(1, name);
        set(2, amendedby);
        set(3, amenddate);
        set(4, consumerlocation);
        set(5, fromdate);
        set(6, todate);
        set(7, ondashboard);
        set(8, hoursbeforepickuptime);
        set(9, stopsale);
        set(10, fkClientplan);
        set(11, type);
        set(12, blend);
        set(13, fkUser);
        set(14, fkOrg);
        set(15, exclusion);
        set(16, fkPlan);
        set(17, fkVirtualpartnerchannel);
        set(18, minimumadvancehours);
        set(19, priority);
        set(20, writeprotectedbyuser);
        set(21, fkPlanDowntown);
        set(22, dashboardchanneltype);
        set(23, cflags);
        set(24, dowStart);
        set(25, startTime);
        set(26, dowEnd);
        set(27, endTime);
        set(28, scheduleType);
        set(29, keyvaluepair);
        set(30, fkClientFinanceGroup);
    }
}
