/*
 * This file is generated by jOOQ.
 */
package jooq.cartrawler_dev_internal.dbo.tables.records;


import javax.annotation.Generated;

import jooq.cartrawler_dev_internal.dbo.tables.T1;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T1Record extends TableRecordImpl<T1Record> implements Record3<String, String, String> {

    private static final long serialVersionUID = 335011214;

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.t1.a</code>.
     */
    public void setA(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.t1.a</code>.
     */
    public String getA() {
        return (String) get(0);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.t1.b</code>.
     */
    public void setB(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.t1.b</code>.
     */
    public String getB() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Cartrawler_dev_internal.dbo.t1.c</code>.
     */
    public void setC(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Cartrawler_dev_internal.dbo.t1.c</code>.
     */
    public String getC() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return T1.T1.A;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return T1.T1.B;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return T1.T1.C;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getB();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getA();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getB();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getC();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T1Record value1(String value) {
        setA(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T1Record value2(String value) {
        setB(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T1Record value3(String value) {
        setC(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T1Record values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached T1Record
     */
    public T1Record() {
        super(T1.T1);
    }

    /**
     * Create a detached, initialised T1Record
     */
    public T1Record(String a, String b, String c) {
        super(T1.T1);

        set(0, a);
        set(1, b);
        set(2, c);
    }
}
